### ISSUE TITLE
Allow SSL-Proxies by reading [X-Forwarded-Host] HTTP-Header

### ISSUE THREAD

**Issue by aagd** [processwire/processwire-requests#101]
### Short description of the enhancement

When using a SSL-Proxy the [X-Forwarded-Host] HTTP header will contain the proxy-hostname. For this case PW should concatenate the hostname to:

`https://ssl.proxy.com/my.domain.com/`

### Current vs. suggested behavior

Currently PW will ignore the [X-Forwarded-Host] HTTP header. When trying to use an SSL proxy the resulting URLs (which are relative to the base URL) will fail while trying to go to:

`https://ssl.proxy.com/page`

while they actually should go to:

`https://ssl.proxy.com/my.domain.com/page`

This also affects all links to assets etc.

### Why would the enhancement be useful to users?

SSL-Proxies are offered by many of hosters for free and allow easy, basic security for accessing admin.

**Comment by ryancramerdesign** [comment]
I don't have a server from which to test this, but I think you may be able to accomplish this from your /site/config.php file:
~~~~~
if(empty($_SERVER['HTTP_X_FORWARDED_HOST'])) {
  if($_SERVER['HTTP_X_FORWARDED_HOST'] === 'my.domain.com') {
    $config->httpHost = 'ssl.proxy.com/my.domain.com';
  }
}
~~~~~
