### ISSUE TITLE
Make appearance of AsmSelect and PageAutocomplete inputfields consistent

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#103]
### Short description of the enhancement

The behaviour of selected options in AsmSelect and PageAutocomplete inputfields is identical - that is, they can be drag sorted and removed by clicking trash icon. The appearance of the options is so similar that the differences that do exist look odd and can make the user wonder if the differences mean anything (they don't). It would be good to follow the "[don't make me think](https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think)" principle and make the appearances consistent by changing PageAutocomplete to match AsmSelect. 

AsmSelect top, PageAutocomplete bottom:

![2017-06-29_124639](https://user-images.githubusercontent.com/1538852/27666883-fa39530e-5cca-11e7-9b7d-3f337e8f440f.png)

**Comment by ryancramerdesign** [comment]
@Toutouwai It looks like this one was already completed awhile ago, as they are both using the same icons when I tested just now. I'll close this out, but let me know if you are still seeing the wrong icon on the autocomplete inputs.

**Comment by Toutouwai** [comment]
In AdminThemeDefault the itemLabel line heights are different and therefore the sortable item heights are different. But I expect most people are using AdminThemeUikit now.

![2021-02-27_090521](https://user-images.githubusercontent.com/1538852/109350071-ca2c3d80-78db-11eb-9a06-f03da444920e.png)
