### ISSUE TITLE
Adding Hooks for Warnings and Errors

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-requests#109]
### Short description of the enhancement

Add hooks for `WireLog::warning` and `WireLog::error`

### Current vs. suggested behavior

Currently, no hooks for warning or error logging.

### Why would the enhancement be useful to users?

A client of mine uses Bugsnag across a suite of their products - ProcessWire has been a recent addition to that arsenal - but there is currently no way to hook into errors to pass exceptions, errors or warnings to a third-party logging API.

**Comment by LostKobrakai** [comment]
It's still V2 of their sdk, but that's how I do it:
```php
// config.php
if($env == 'production'){ // Fast disable
	$bugsnag = new Bugsnag_Client($config->credentials['BUGSNAG_NOTIFIER']);
	$bugsnag->setErrorReportingLevel(E_ALL & ~E_NOTICE);
	set_error_handler(array($bugsnag, 'errorHandler'));
	set_exception_handler(array($bugsnag, 'exceptionHandler'));
	register_shutdown_function(array($bugsnag, 'shutdownHandler'));
	$bugsnag->setReleaseStage($env);

	$config->bugsnag = $bugsnag;
}

// init.php
$bugsnag = $this->config->bugsnag;
if(!$bugsnag instanceof Bugsnag_Client) return;

$bugsnag->setUser(array(
	'name' => $this->user->usr_fullname,
	'email' => $this->user->email,
	'id' => $this->user->id
));

$this->wire()->addHookBefore('Wire::trackException', function(HookEvent $e) use ($bugsnag) {
	$bugsnag->notifyException($e->arguments(0), array(
		'additionalText' => $e->arguments(2)
	), $e->arguments(1) ? 'error' : 'warning');
});

$this->wire()->addHook('Wire::bugsnagError', function(HookEvent $event) use ($bugsnag) {
	call_user_func_array([$bugsnag, 'notifyError'], $event->arguments());
});

$this->wire()->addHook('Wire::bugsnagException', function(HookEvent $event) use ($bugsnag) {
	call_user_func_array([$bugsnag, 'notifyException'], $event->arguments());
});
```

The latter hooks really are just convenice and not really needed if trackException is used in the project.

**Comment by ethanbeyer** [comment]
Ahhh, nice!

Thanks, @LostKobrakai ! Would you say that this closes this request or nah?

**Comment by LostKobrakai** [comment]
Depends on if trackException is what you looked for.

**Comment by ethanbeyer** [comment]
I had seen `Wire::trackException()` as a hookable function but I don't know much about what it does yet.

(You don't need to explain, I will look at the code to see when it gets called and the documentation for that as well.)

It had just seemed to me that `Wire::error()` and `Wire::warning()` didn't use `Wire::trackException()` at any point.
