### ISSUE TITLE
Making Translations more intuitive

### ISSUE THREAD

**Issue by dennisspohr** [processwire/processwire-requests#110]
### Short description of the enhancement

If you have many files to translate, it's a quite long list of files and it's time-consuming finding missing translation in case of updates to the files.

### Current vs. suggested behavior

Currently, after I did some changes to my template-files, I have to go through all files finding missing translations. In that case I scroll through the list searching for something like "27 phrases (1 blank)". Then I open all of them in a new tab and complete the translations. However, it also finds translations which I already did where the text is the same in both languages.

For example "Downloads" => "Downloads". The text is the same, but after saving it will still show as "blank".

### 2 Suggestions

1. A filter for finding files with blank translations
2. Don't show translations, which has the same text in both languages, as blank.

### Why would the enhancement be useful to users?

It would save a lot of time while developing a project in multiple languages.

### Optional: Screenshots/Links that demonstrate the enhancement

![image](https://user-images.githubusercontent.com/10246331/29004339-19a7b5a0-7ac6-11e7-8fb4-547ddb989be5.png)

![image](https://user-images.githubusercontent.com/10246331/29004346-2ae43f82-7ac6-11e7-9f2d-4883d432997f.png)

**Comment by LostKobrakai** [comment]
> Don't show translations, which has the same text in both languages, as blank.

Putting a `=` into the translation field does result in that.

**Comment by dennisspohr** [comment]
Awesome, LostKobrakai, thanks for the information. Didn't know that.

However a filter like "Only show files with blank translations" would be great!

**Comment by andoro** [comment]
@dennisspohr I totally agree with your point...
If you try to translate PW to a new language or just fix an existing language pack, it's very hard to do that at the moment.

My thoughts:

1. It would be nice also if I could mark a file as translated/final.
2. I'm also missing from admin a kind of file list, which would tell me which files were used during rendering a page. So I could guess where should I find the translatable string for each strings.
3. The Live search feature works very well, but I can search only for translatable strings! What if I need to change/update/fix a translation? I don't know what is the original phrase I see only the translated string. So it would nice If Live would find the translated strings too, or if this search target would be selectable.

**Comment by jmartsch** [comment]
@dennisspohr I think this issue is resolved and should be closed. Do you agree?
