### ISSUE TITLE
hookable InputfieldPage::getPageLabel

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#112]
Make **InputfieldPage::getPageLabel** hookable.

Reason: https://processwire.com/talk/topic/16970-modify-custom-page-label-format-via-hookapi/

**Comment by jlahijani** [comment]
Bump.  Is it possible for this to be implemented?

**Comment by Toutouwai** [comment]
Support for this was added recently: https://github.com/processwire/processwire-requests/issues/460
