### ISSUE TITLE
Make Inputfield::renderReady hookable

### ISSUE THREAD

**Issue by gingebaker** [processwire/processwire-requests#12]
Would it be possible to make the renderReady function in Inputfield Core class hookable?
https://github.com/processwire/processwire/blob/master/wire/core/Inputfield.php#L1030
I could not find another way to add Javascript or CSS to Inputfields when the Inputfield is loaded via Ajax (Repeaters or loadedByAjax).

More info here on my forum post:
https://processwire.com/talk/topic/14187-inputfieldrenderready-hook-alternative/

I think it would be useful if someone doesn´t actually want to add/extend an existing inputfield, but only add some special additions to the existing via hooks. I personally would need it for a module that adds another kind of upload tool to the current InputfieldImage. (PlUpload). I need to add some JS and CSS. 

Perhaps there is another way of doing such things, but I could not find any till now?

Thank you!

**Comment by ryancramerdesign** [comment]
We've got something very much like it, which would be the `InputfieldWrapper::renderInputfield` hook. This is the method that ultimately calls the renderReady() method that you are wanting to hook. You could hook it like this:

~~~~~
$wire->addHookBefore('InputfieldWrapper::renderInputfield', function($event) {
  $inputfield = $event->arguments(0);
  if(strpos($inputfield->className(), 'InputfieldImage') === 0) {
    // good to go
  }
}); 
~~~~~

**Comment by gingebaker** [comment]
Hi Ryan. Thanks for the answer. I tried this hook. It works for me on ajax loaded fields (collapsed attribute) but not in repeaters wich items are setup to load all dynamically via ajax. It looks like the Hook does not get called?

I am seeing this call here:
https://github.com/processwire/processwire/blob/master/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module#L205
wich looks like In Repeaters the renderReady is called directly!?

**Comment by gingebaker** [comment]
Hi @ryancramerdesign 
Any changes that you can make Inputfield::renderReady hookable? As mentioned in the previous post I cannot load the js and css files with the InputfieldWrapper::renderInputfield hook you suggested.

With your hook it works perfectly on ajax loaded fields but not on Fields wich are in ajaxLoaded RepeaterItems.

I am working on a module wich adds clientside image resizing to the Standard InputfieldImage. It works so far, but I cannot load the needed JS and CSS files correctly in ajaxLoaded RepeaterItems. For sure I could load the JS/CSS on every edit screen, but I want to avoid this ;)

Do you need more detailed information why it´s not working? 

Thanks!
