### ISSUE TITLE
Data column for pages table

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#123]
### Short description of the enhancement

This is a tentative request, because I expect there is some good reason why this hasn't already been done...

Could there be a 'data' column added to the 'pages' table, similar to what is provided in the 'fields' and 'templates' table? The thinking is that this column could be used by modules that need to store some setting for certain pages. It wouldn't be for anything that needs to be queried by PageFinder.

Currently a module that wants to store some setting for a page has to either:

- Create some field and request that users add it to templates. This is totally impractical, of course. A global field would be an alternative, but a very undesirable one.
- Create and manage its own database table for storing the settings. This is okay, but it adds significantly to the complexity of the module and the level of knowledge that is required to develop it.

Having a JSON data column that loads any saved settings as properties of $page would make things a lot easier for module developers.

**Comment by adrianbj** [comment]
I haven't really thought this through, but my initial thought is that it sounds very useful. If it's not available as a property of $page though, how do you propose accessing it?

Just wanted to note (for completeness) that I often store page specific settings in the module's JSON. It works pretty well, but there is always the possibility of going beyond the `TEXT` limitations of the module table's data field, although probably not in many situations.

**Comment by Toutouwai** [comment]
> If it's not available as a property of $page though, how do you propose accessing it?

I'm proposing that settings in the data JSON would be automatically loaded as properties of $page - the equivalent to what is done for Template and Field objects. The difference to normal page fields is that there wouldn't need to be support for PageFinder, so you couldn't do `$pages->find("some_module_setting=foo")`. There would be an onus on the module developer to use such a feature responsibly to minimise impacts on performance.

> Just wanted to note (for completeness) that I often store page specific settings in the module's JSON.

Thanks, that's a helpful suggestion that I can use for the time being. Which of your modules would be a good one to look at to see how you are managing this? Do you hook `Pages::delete()` to remove settings that are no longer needed?

**Comment by adrianbj** [comment]
> I'm proposing that settings in the data JSON would be automatically loaded as properties of $page - the equivalent to what is done for Template and Field objects.

Sorry, I must have totally misread your initial post - I thought you said it wouldn't be available as a property of `$page`.

> Which of your modules would be a good one to look at to see how you are managing this? Do you hook Pages::delete() to remove settings that are no longer needed?

Both Batch Child Editor and Page Protector take this approach, although I haven't bothered with hooking Pages::delete(). Typically the page specific settings aren't large enough to worry about if they are left behind, although it's probably not a bad idea, but in the case of BCE which isn't autoloaded on the frontend, it wouldn't deal with pages deleted via the API anyway.

**Comment by Toutouwai** [comment]
I think this is now covered by the $page->meta() method.
https://processwire.com/blog/posts/pw-3.0.133/
