### ISSUE TITLE
Module file names and class loading

### ISSUE THREAD

**Issue by mikerockett** [processwire/processwire-requests#129]
### Short description of the enhancement

Something that’s been on my mind for a while now (and apologies if this has been brought up before) is the ability to simplify our module filenames. I’ve never been so keen on repeating my module class name in the various filenames (I use JSON info files and ModuleConfig), and so it’d be really great if we had the option of using purpose-based names, such as:

- module.php
- info.json
- config.php

In light of new filenames, I thought it might also be a nice idea to have an autoloaded classloader file called `loader.php` that uses an array to pass instructions to the class loader. Ex:

```php
<?php

return [
    'Vendor\Namespace' => 'src/Namespace',
];
```

### Why would the enhancement be useful to developers?

At the end of the day, the module is identified by its directory name, and so I see only repetition here. Sure, back when info and config files did not exist, this wouldn’t have been such an issue in my mind.

Regarding the class loader, this is just something that popped into mind whilst writing this request, and I think it could be quite handy to module developers. I, for one, make consistent use of the class loader, so I’d be amped to see this enhancement.

**Comment by adrianbj** [comment]
I like this in priciple, but what about modules that bundle more than one module together? Many have helper Process modules. How would these be handled?

**Comment by mikerockett** [comment]
Ah, didn’t think about that… I’d be inclined to say that:

a) each sub-module has its own folder with the above structure _or_
b) it can be ignored altogether, and PW will pick it up anyway (as it currently does).

At the end of the day, this would be optional, and according to developer preference.

**Comment by mikerockett** [comment]
Oh, and:

c) The main module could still be called module.php as it’s identified by both the directory it lives in, as well as the classname. As such, helper modules could also reside in the root with their full names. My only issue is that it would be somewhat inconsistent, and so they could also be placed in a directory called `submodules`, for example. Truthfully, though, I prefer (a).
