### ISSUE TITLE
Do not limit length of $input->urlSegment() to 128 characters

### ISSUE THREAD

**Issue by weberhofer** [processwire/processwire-requests#130]
### Short description of the enhancement

Currently the maximum length of a segment is limited to 128 and can not be changed. A enhancement could make that max-size configurable or remove the limitation of the length completely.

### Current vs. suggested behaviour

I'm using the segment to allow downloads of files from external sources. Currently it's not possibly when file-names are more than 128 characters long.

Reference: https://processwire.com/talk/topic/17677-length-of-input-urlsegment-limited-to-128-characters/

**Comment by ryancramerdesign** [comment]
This has been added in 3.0.86. Thanks.

**Comment by weberhofer** [comment]
Thank you! I have updated my staging system and the change works as expected.
