### ISSUE TITLE
Enhance wireBytesStr()

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#133]
### Short description of the enhancement

Pagefile::filesizeStr() uses [wireBytesStr()](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/core/Functions.php#L627-L638) to return a human-readable file size string, but it's locked to kB and not configurable. A value in kilobytes is not ideal if your file is, say, 100MB or more.

Of course it's possible to use a custom function ([example](http://jeffreysambells.com/2012/10/25/human-readable-filesize-php)) to covert bytes to a human-readable string but it would be nice to have an enhanced function in the core.

**Comment by adrianbj** [comment]
Completely agree - I use a custom function quite often for the same reason.

**Comment by ryancramerdesign** [comment]
Thanks, I have upgraded the wireByesStr() function have more units and options.

**Comment by Toutouwai** [comment]
Thanks!
