### ISSUE TITLE
Make SVG images in lister respect the image width/height configuration setting

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#139]
In ListerPro (or regular lister), you have the option to set the Image Width and Image Height.  This works well for png, jpg, etc.  But it doesn't apply for SVG, and it would be nice if it could, perhaps through the "height" or "width" attirbute in the IMG element (since they are vectors and not raster).

**Comment by adrianbj** [comment]
This PR of mine: https://github.com/processwire/processwire/pull/92 might help out.

**Comment by jlahijani** [comment]
For now, I'm sizing it via custom admin css:

**admin.php:**
```
$config->styles->append($config->urls->templates."admin.css");
```

**admin.css:**
```
.ProcessPageListerPro .ProcessListerTable img {
  display: block !important;
  width: 200px !important;
  height: auto !important;
}
```
