### ISSUE TITLE
Group File Compiler Notification Messages

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-requests#141]
### Short description of the enhancement

If possible, I would like to see the FileCompiler messages grouped in the notifications listings.  I'm not sure if this is handled in core Processwire or if it is up to modules to implement this?

### Current vs. suggested behavior

Currently a notification is listed for each compiled file.  It would be nice if these were grouped together.

### Why would the enhancement be useful to users?

It would collapse the FileCompiler notifications into just one expandable message taking up far less vertical page space.

### Optional: Screenshots/Links that demonstrate the enhancement
![upgrades](https://user-images.githubusercontent.com/40570/33773605-162aa48e-dbfe-11e7-9164-72a6248d0a17.jpg)

**Comment by gmclelland** [comment]
I mainly see these types of messages when upgrading modules with the ProcessWireUpgrade module.

**Comment by ryancramerdesign** [comment]
I added collapsed notifications to AdminThemeUikit in 3.0.85 a couple weeks ago and I think it should accomplish roughly what you are looking for. Note however that you should expect to see these kinds of notifications when upgrading modules or installing modules that don't use a ProcessWire namespace, but they will only appear if you are logged in as superuser.

**Comment by gmclelland** [comment]
I just upgraded to 3.0.85 and it works as you mentioned.  Thanks Ryan!
