### ISSUE TITLE
Documentation request: advanced mode

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-requests#148]
In a nutshell this request is about documenting somewhere what `$config->advanced` does / enables / includes. Current documentation is rather lacking in this regard, so it's hard to say exactly what might be hidden behind this flag.

Additionally it might be worth adding some clarifications, such as when should one use this mode, and do changes made in advanced mode persist even after it has been toggled off.

**Comment by jmartsch** [comment]
Yes please

**Comment by ryancramerdesign** [comment]
@teppokoivula Thanks, I have added this.

**Comment by teppokoivula** [comment]
@ryancramerdesign, thank you! Looks great.

Only thing I'm wondering is that should/could the docs clarify what happens after advanced mode is disabled?

Perhaps it's just me, but I originally found it a little unclear if the changes made in advanced mode stay active.

**Comment by ryancramerdesign** [comment]
@teppokoivula This is actually the primary purpose of advanced mode, to enable you to apply some settings that you can't usually. So a common case is to enable it to it temporarily to apply something needed, then disable advanced mode once you are done, so that the setting is then locked in. I'm not sure I understand about having changes no longer be active if advanced mode is disabled? Is there a specific case you are thinking of?

**Comment by teppokoivula** [comment]
@ryancramerdesign, what I'm trying to say is that at least when I first read about advanced mode it wasn't obvious if I could enable it, make some changes, and then disable it without loosing the changes I'd just made. In fact my first impression was that I'd have to leave advanced mode on indefinitely, which in turn didn't seem like a good idea.

I'm just saying that it might be worth clarifying that the changes *do* indeed stick around even after you disable advanced mode 🙂

**Comment by adrianbj** [comment]
I had a similar impression to @teppokoivula - wasn't really sure about how that would be handled.

I am curious why it's a bad idea to leave Advanced mode enabled though - if I am the only superuser then what impact does it have on other users? How could they break anything? This is one reason why I asked a long time ago to remove the "Advanced mode" note at the bottom of the admin for non-superusers. If I am correct it doesn't impact them and they don't know what it means.

Or does it impact them in some way I have never noticed?

**Comment by jmartsch** [comment]
Please also take a look at my request that advanced mode should be enabled by default (at least for superusers): https://github.com/processwire/processwire-requests/issues/381

**Comment by teppokoivula** [comment]
@ryancramerdesign, I'm closing this request since there is now a docs page — thank you! — but I still feel like this one nuance could be spelled out more clearly:

> I'm just saying that it might be worth clarifying that the changes do indeed stick around even after you disable advanced mode 🙂

Perhaps something like this:

> Please note that if you disable advanced mode later on, any changes you have made to options that are enabled/visible only in advanced mode will stay in effect. It is generaly recommended that you enable advanced mode temporarily, change relevant options, and then disable it.

At least for me it was not obvious if this is the case, and stating it in the docs would clear this up hopefully once and for all.
