### ISSUE TITLE
Add @since to API documentation

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#158]
### Short description of the enhancement

Please add [@since](http://docs.phpdoc.org/references/phpdoc/tags/since.html) to the API documentation, at least for new methods and properties going forward.

I used the Inputfield `hasPage` property in a publicly-shared module, not knowing that it was only added to the core in PW 3.0.66 (only discovered by digging back through the commit history) while the current master is 3.0.62.

### Why would the enhancement be useful to users?

Will avoid confusion for users with less than the current dev version wondering why documented API methods/properties aren't working for them.

Module developers will be able to tell what versions of PW their module will be compatible with according to the methods and properties they are using.

This is also important because there can be a long time between stable releases (currently 38 versions and counting) with many new methods/properties added in that time.

**Comment by ryancramerdesign** [comment]
@Toutouwai I've been doing this for a couple years now at least. If there are any I've missed then it was accidental. But I'm going to close this one out since it's a few years old and "since" tags are standard in PW additions.
