### ISSUE TITLE
Admin UIKIT - do not hide "view site" under Account

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-requests#164]
In Admin UIKITI I would not hide "View Page" under the account menu.

<img width="185" alt="bildschirmfoto 51" src="https://user-images.githubusercontent.com/652879/37290915-c2cc2272-260d-11e8-8746-30b2be106e68.png">

"View Site" is a separate thing (has nothing to do with the account info) and is something that needs to be clicked often and should be easily accessible.

Actually "Accounts" is a bit prominent in the top bar and could go into the footer?

**Comment by Toutouwai** [comment]
Some related discussion in this post and some that follow: https://processwire.com/talk/topic/17786-pw-3084-%E2%80%93-core-updates-installer/?do=findComment&comment=156507

**Comment by tbba** [comment]
too old

**Comment by jmartsch** [comment]
Please reopen, it is old, but still valid
