### ISSUE TITLE
Make the dropdown list of save actions in Page Edit hookable

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#168]
### Short description of the enhancement

It would be handy if the items in the dropdown list of save actions in Page Edit were created via a hookable method so that custom actions could be added.

To be clear, I'm not requesting any special support for custom actions besides allowing custom labels and values in the dropdown - it would be up to the developer to handle any custom actions by checking the value of `_after_submit_action` in POST.

### Why would the enhancement be useful to users?

It would open up possibilities for custom after-submit actions that depend on the user making a choice to execute that action. Better to use the existing dropdown for this than have to reinvent the wheel with additional custom buttons or dropdowns.

**Comment by elabx** [comment]
+1

**Comment by netcarver** [comment]
Could this hook, if added, also allow removal of actions (even all of them)?

**Comment by ryancramerdesign** [comment]
@Toutouwai @elabx @netcarver This feature was added back in 3.0.142. I'll demonstrate how to use it in the weekly update post later today.

**Comment by Toutouwai** [comment]
Thanks for adding this and also the tutorial.

**Comment by jmartsch** [comment]
To which method do I need to attach the hook?

**Comment by BernhardBaumrock** [comment]
Its in the post of 19.02.2021 https://processwire.com/talk/topic/25155-weekly-update-%E2%80%93-19-february-2021/
