### ISSUE TITLE
Make has_parent support piped OR values

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-requests#17]
> Briefly describe the enhancement or the feature request.

Allow for selectors to work with these: `has_parent=1234|1235`

> What is the current and suggested behavior?

Currently only this does work: `(has_parent=1234), (has_parent=1235)`.
The Selector parser could probably handle both cases by simply handling the shortform like the longer form.

> Why would the enhancement be useful to users?

Sometimes one might to select pages from different branches in the page-tree

More information here: https://github.com/ryancramerdesign/ProcessWire/issues/1232

**Comment by phlppschrr** [comment]
Should already work like suggested, at least Ryan posted this last year on the blog:
https://processwire.com/blog/posts/processwire-core-and-profields-updates-2.5.22/#has_parent-selectors-now-support-multi-value

**Comment by LostKobrakai** [comment]
So often as this has bitten me on 2.7.3 it's certainly not working anymore.

**Comment by netcarver** [comment]
Should be fixed by https://github.com/processwire/processwire-issues/issues/182. Closing.
