### ISSUE TITLE
gophp71 for PW 3.1?

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#171]
### Short description of the enhancement

Just wondering what you think about maybe giving PW 3.1 a minimum requirement of PHP 7.1?

Not sure if it's a good idea or not, but I do like the sentiment behind https://gophp71.org/ - the old gophp5 movement was helpful at a time when PHP 4 really needed to die. Maybe PHP 5 is not so bad, but I'd still like to see more of a push towards 7.

**Comment by ryancramerdesign** [comment]
Definitely plan to do this, but since there's no technical requirement for PHP 7.x just yet, I'm going to wait for this change to accompany a major version (whatever the next one is).
