### ISSUE TITLE
Chain API Calls

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-requests#175]
jQuery's beauty lies in it's ability to chain calls. Every method that only sets something without returning a value is chain-able like so:

```
// sets color and link, returns text;
var text = $('a').css('color','red').attr('href','http://google.com').hide().text();
```

I think, this should be possible with PHP as well (at least with newer versions) and would add to the beauty of Processwire:

```
$pages->get('title=Test')->of(false)->set('title','Hello World')->save();
```

One would only need to return the object for each method at the end…

### Current vs. suggested behavior

```
// current
$page->of(false);
$page->set('title','Hello World');
$page->save();
```

```
// suggested
$pages->of(false)->set('title','Hello World')->save();
```

### Why would the enhancement be useful to users?

It would simplify writing code for not so complex things…

**Comment by adrianbj** [comment]
Mostly you can - this works:
```
$pages->get('title=Test')->setAndSave('title','Hello World');
```

There were two issues with your code - using `$page` instead of `$pages` and using `of(false)` which does return a boolean, hence it can't proceed.

**Comment by adrianbj** [comment]
Actually, this also works because `setOutputFormatting()` doesn't return anything.
```
$pages->get('title=Test')->setOutputFormatting(false)->set('title','Hello World')->save();
```

**Comment by adrianbj** [comment]
@noelboss - are you happy closing this?

**Comment by netcarver** [comment]
Closing now.
