### ISSUE TITLE
WireCache expire by multiple templates

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-requests#182]
### Short description of the enhancement

WireCache can cache anything returned by the function. There is chance that we would want to cache the result from more than one template. The WireCache can only allow single template to trigger the expire now.

### Current vs. suggested behavior

The current behavior only allows only single template to trigger the cache to expire. I suggest to allow array of templates to trigger the cache expiration.

### Why would the enhancement be useful to users?

The case I found that we need to cache is mostly not $pages->find, but the foreach afterward instead. We may then process other template data depending on the first template data to output something. In this case, we are using more than one template for the output. If we can only define one template to trigger the expiration, we lose control of the other templates, which also has chance to get data update.

**Comment by Toutouwai** [comment]
> The WireCache can only allow single template to trigger the expire now.

You can pass in a selector for the expires argument and include as many templates as you need in that selector.
https://processwire.com/blog/posts/processwire-2.6-rc1-2.5.29-and-more/#whats-new-this-week-processwire-2.5.29

**Comment by karltdev** [comment]
Thanks you @Toutouwai. I have missed this blog post. Maybe we could have section in the API reference documentation that has the related blog post added.

[https://processwire.com/api/ref/cache/get/](https://processwire.com/api/ref/cache/get/)
