### ISSUE TITLE
$user->isLoggedin() does not follow Camel Case conventions

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-requests#184]
### Short description of the enhancement

[`$user->isLoggedin()`](http://processwire.com/api/ref/user/is-loggedin/) does not follow the normal Camel Case naming conventions.

### Current vs. suggested behavior

Rename `isLoggedin()` to `isLoggedIn()`.

### Why would the enhancement be useful to users?

Follows established naming conventions throughout the Core.

### Optional: Screenshots/Links that demonstrate the enhancement

http://processwire.com/api/ref/user/is-loggedin/

**Comment by Toutouwai** [comment]
I agree with what you're saying. Although the case used in the method name (when declared and when called) has no actual effect because function/method names are not case sensitive in PHP. So if you call the method as `isLoggedIn()` or even as `ISLogGEdiN()` it will still work.

**Comment by ethanbeyer** [comment]
Well, color me embarrassed - I did not know that case did not matter in declarations or calls!

**Comment by adrianbj** [comment]
Not saying I agree, but an interesting read: https://www.tonymarston.net/php-mysql/case-sensitive-software-is-evil.html

**Comment by ethanbeyer** [comment]
I'm closing this since it's literally just preference at this point :D
