### ISSUE TITLE
ProcessPageClone: add config option to always use clone form

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#186]
### Short description of the enhancement

When cloning a page with ProcessPageClone, if the page has children the user sees a form where they can specify a title, name, published status, and whether or not child pages should be cloned.

But when cloning a page without children the user doesn't see this form. Not sure why that is, because only the last input in the form relates to children and the other form inputs can be useful to the user who is cloning a childless page.

This request is for a config option in ProcessPageClone to always show the form to the user regardless of whether the page has children or not.

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, I have added that option as a configuration setting with the module, so you can now configure it to always use the full clone form if you want to.

**Comment by Toutouwai** [comment]
Thanks for adding this @ryancramerdesign
