### ISSUE TITLE
Add $config property to extend MySQL init command

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-requests#19]
### Short description of the enhancement

Add a $config property that allows to add SQL commands to be performed on every database connect.
### Optional: Steps that explain the enhancement

In WireDatabasePDO::getInstance and Datebase::__construct, check if a property $config->dbInitCommand is set. If yes, merge this after the builtin `SET NAMES '$charset'` command passed as with a semicolon.
### Current vs. suggested behavior

Currently, only the `set names` statement is executed for each connection, and there's no means to add SQL code to that (at least that I know of).

Alternatively, hard-coding a `set timezone` command that sets the connection timezone to PHP's value might be a viable solution too (and even make sense to keep consistence when migrating between systems with different settings), but that might be breaking change for upgrading existing installations.
### Why would the enhancement be useful to users?

I'm currently working on a [module to enhance selectors for datetime fields](https://github.com/BitPoet/DatetimeAdvanced). To work reliably, the MySQL connection needs to be aware of the timezone used by PHP (`set time_zone = 'TIMEZONE-OF-PHP'`). This can only be assured if the `set time_zone` command is executed for every connection.

Since the performance impact of such a change should be negligible and there is no hook to accomplish this, and there is definitive interest in my module ([see module announcement](https://processwire.com/talk/topic/14354-fieldtypedatetimeadvanced-subfield-selectors-for-datetime/) and [initial discussion](https://processwire.com/talk/topic/14345-find-upcoming-birthdays/)), I'm hopeful this change can be incorporated.

Thanks for taking the time to read and think through this.

**Comment by LostKobrakai** [comment]
This would also solve the issue for create/update timestamps being incorrect: https://github.com/ryancramerdesign/ProcessWire/issues/1989

**Comment by BitPoet** [comment]
Closing this issue as the dbInitCommand property has been added with commit processwire/processwire@6b64a480b8699e3f438905af92d52ca1bdbd7a41
