### ISSUE TITLE
Add http proxy support 

### ISSUE THREAD

**Issue by salvw** [processwire/processwire-requests#190]
### Short description of the enhancement

Add support for a http proxy in WireHttp.

### Current vs. suggested behavior

On my webhost external http traffic has to go through a proxy. So, for me update checks fail and I can't install modules directly.

Maybe add API support in WireHttp and a config option like the following in Wordpress:
`define('WP_PROXY_HOST﻿', 'proxy.domain.com');`
`define('WP_PROXY_PORT', '8080');`

I can make the update check work when i add the following to line 461 of WireHttp.php but the downloads still fail.
`'proxy' => 'tcp://proxy.domain.com:8080',`
`'request_fulluri' => true`

### Why would the enhancement be useful to users?

It would enable easy updates and easy installation of modules when behind a proxy.

**Comment by ryancramerdesign** [comment]
I wasn't aware of this setup for web hosts. How common is it? If WP is
accounting for it, we probably should too. Seems like a worthwhile
addition.

**Comment by tiefenb** [comment]
We have also to use proxies in our webhost. Would like to see this feature in pw core

**Comment by salvw** [comment]
This is solved for me by [this](https://github.com/processwire/processwire/commit/f9ded64ba36ad1bcf4f29c8cc7afd0773ecb7454#diff-1972780faf7a13076c1284fbb478144a) update.

**Comment by matjazpotocnik** [comment]
@salvw can this be closed?
