### ISSUE TITLE
Ability to remove page from page field by ID

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#198]
### Short description of the enhancement

It would be great to be able to do:

```
$page->pagefield->remove(nnnn);
```

rather than having to do:
```
$page->pagefield->remove($pages->get(nnnn));
```

### Why would the enhancement be useful to users?

Mostly because of consistency with the `add` method which lets you use the ID directly.

For more info, see here:
https://processwire.com/talk/topic/5013-how-to-delete-a-page-in-page-field-multiple-pages-pagearray/

**Comment by Toutouwai** [comment]
Ryan has talked a bit about this here: https://github.com/processwire/processwire-issues/issues/486#issuecomment-363056670

**Comment by adrianbj** [comment]
Thanks @Toutouwai - I'll close this then. I am not sure that Ryan's suggestion of a selector eg `"id=123"` would really be that helpful - it's just another option to remember.

**Comment by szabeszg** [comment]
> I am not sure that Ryan's suggestion of a selector eg "id=123" would really be that helpful - it's just another option to remember.

I guess the main reason is this: _"An index and a page ID are both integers, so remove() can't support both."_
