### ISSUE TITLE
Admin ajax search and Trashed pages

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#201]
### Short description of the enhancement

Hey @ryancramerdesign - any chance we could have the option to NOT return trashed pages, or at least have a label in the returned results that indicated it's in the trash?

### Why would the enhancement be useful to users?

If you have an old copy of a page in the trash and a new one in the main page tree, you can't tell which is which until you click on them.

**Comment by Toutouwai** [comment]
A hook for the meantime...
```php
$wire->addHookAfter('ProcessPageSearch::findReady', function(HookEvent $event) {
    $event->return .= ', status!=trash';
});
```

**Comment by Toutouwai** [comment]
>  ...or at least have a label in the returned results that indicated it's in the trash?

```php
$wire->addHookAfter('ProcessPageSearch::executeFor', function(HookEvent $event) {
    $json = $event->return;
    $data = json_decode($json, true);
    foreach($data['matches'] as $key => $match) {
        if(isset($match['path']) && strpos($match['path'], '/trash/') === 0) {
            $data['matches'][$key]['title'] = '(trashed) ' . $match['title'];
        }
    }
    $event->return = json_encode($data);
});
```

**Comment by adrianbj** [comment]
Nice @Toutouwai!

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign for this and all the other recent search improvements!
