### ISSUE TITLE
Passwordfield: add unmasking button instead of confirm field

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-requests#203]
### Get rid of the confirm password field and use an unmasking button instead

Many articles like http://uxmovement.com/forms/why-the-confirm-password-field-must-die and recent user studies show, that there are UX problems with a confirm password field.

Also there are comments who disagree with this behaviour.

An example of a good password field UX is the signup form of MailChimp
https://login.mailchimp.com/signup/

Luke Wroblewski from Google also described the problems with masked password fields, especially for mobile users: https://www.lukew.com/ff/entry.asp?1653

### Why would the enhancement be useful to users?

A confirm password field does not really add verification that you typed your password correctly. Users tend to make the same typing errors again, if they repeat their password.

It would be better to use a show/hide password button, so a user can see the password he typed. This would remove friction and frustration.

Luke even wrote, that he displays people’s passwords by default in the Polar app.
I did not implement this at the time, but think it is a smart move.
Maybe I implement it as an option.

### Fully functional module is ready ###
Right now I have a working InputfieldPassword to use with AdminThemeUikit.
Please see the following screencast and tell me if you are interested in implementing this.
The source code is available at my post https://processwire.com/talk/topic/19462-inputfieldpassword-with-unmasking-button-instead-of-confirm-field/

Here is a video of the new Inputfield in action: 

https://youtu.be/PEWp89TOUsU

**Comment by ryancramerdesign** [comment]
@jmartsch Thanks, I have added support for this. I agree on the benefits of having an unmask option. I don't agree with dropping confirmation inputs or the stated justifications for that. In any case, having an unmask option seems like a benefit either way, letting the user decide when the environment is appropriate. At the moment, you have to enable it in your password field settings. But maybe having the option to unmask should be enabled by default? I'd just like to make sure all works as intended first but then maybe it should be an option by default.

**Comment by jmartsch** [comment]
>  I'd just like to make sure all works as intended first but then maybe it should be an option by default.

I don't see a problem with making it default. I checked in latest Chrome, Edge and Firefox (Windows 10), and it works fine.

**Comment by matjazpotocnik** [comment]
@jmartsch, can this be closed?
