### ISSUE TITLE
Datepicker field (PW and form) with a "Today" button?

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-requests#205]
Is there any chance for a datepicker inputfield with a "Today" (or a "Now") button?

**Comment by Toutouwai** [comment]
A "Now" button is shown if your Datetime field has a time input format set.

![2018-06-27_121521](https://user-images.githubusercontent.com/1538852/41945932-e715308e-7a03-11e8-88bd-3339f000930f.png)

So what is needed is a "Today" button for date-only fields.

**Comment by tbba** [comment]
Toutouwai thank you - the "Today" is actually the one needed (the mentioning of "Now" was not properly double checked by me, sorry)
