### ISSUE TITLE
Use CKEditor 5 in ProcessWire

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-requests#217]
### Why?
It is simply amazing, has an improved user experience, is more lightweight, better looking and has nicer features.
Almost everybody will profit.

From the [docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/whats-new.html):
We simplified the integration of the editor into your system.

We feel that in previous editor versions we had way too many features and configurations. This was confusing developers and at the same time negatively impacting the end user experience.

In CKEditor 5 misleading formatting tools were removed, dialogs were stripped out or simplified in favor of well-designed features that require no configuration.

Lightweight
The editor is much more lightweight and fast. It brings a fantastic user experience on both desktop and mobile devices.

You also wrote in the blogpost https://processwire.com/blog/posts/pw-3.0.80/#a-look-at-the-upcoming-ckeditor-5 that you may want to integrate it into PW.

**Comment by mustafa-online** [comment]
It feels and look great, i hope we see it soon in "**PW**" core.

**Comment by fuzenco** [comment]
Yes please!

**Comment by szabeszg** [comment]
Please read this blog post: https://processwire.com/talk/topic/19822-integrate-ckeditor-5-into-processwire/?do=findComment&comment=175046

**Comment by jmartsch** [comment]
Please read also my comment https://processwire.com/talk/topic/19822-integrate-ckeditor-5-into-processwire/?do=findComment&comment=175111 why CKEditor 5 may not be a good option for ProcessWire. Because it has many restrictions.
Maybe it could be implemented as an addition to CKE4
