### ISSUE TITLE
Allow setting downdown items to InputfieldSubmit instance

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-requests#220]
### Short description of the enhancement

The InputfieldSubmit module does not allow setting dropdown items from outside due the fact that `$dropdownItems` is being [**_protected_**](https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldSubmit/InputfieldSubmit.module#L33). After I set `$dropdownItems` to be public, I can add any dropdowns  successfully.

### Why would the enhancement be useful to users?

The submit button should be able to add dropdown items as the code is already [**_there_**](https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldSubmit/InputfieldSubmit.module#L160-L207). The dropdown button is neat for buttons with multiple actions.  Instead of showing many different buttons, allowing flexible amendment to dropdown button is a great plus to custom admin UI.

This could also help #168.

**Comment by matjazpotocnik** [comment]
@karltdev, issue/feature request 168 is now fixed/completed. Can this feature request be closed now?
