### ISSUE TITLE
Avoid reading the whole uploaded file into memory at once in the WireUpload class

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-requests#233]
### Short description of the enhancement

Currently when using Ajax uploads, WireUpload slurps the whole uploaded file into memory. This is a problem in scenarios where very large files need to be uploaded. A chunked retrieval would make the script much more memory efficient.

### Current vs. suggested behavior

Currently, everything happens in the [following line](https://github.com/processwire/processwire/blob/c55a5474581ae694b91cb99c55cb60c9d0286a93/wire/core/WireUpload.php#L290):

```php
		file_put_contents($tmpName, file_get_contents('php://input')); 
```

It would be nice to cut down on used memory and read/write the contents in chunks of a certain size, balancing between memory usage and cpu+disk cycles. This is a suggested solution using a chunk size of 8MB:

```php
		$inputHandle = fopen("php://input", "rb");
		$outputHandle = fopen($tmpName, "wb");
		while(! feof($inputHandle)) {
			$filedata = fread($inputHandle, 8192 * 1024);
			fwrite($outputHandle, $filedata);
		}
		fclose($outputHandle);
		fclose($inputHandle);
```

### Why would the enhancement be useful to users?

I have a practical case where movies (MP4) of more than 100MB need to be uploaded to pagefiles. These uploads sometimes break memory limits or seriously slow down the server. Others will likely experience similar issues when uploading large files (like vidoes or compressed archives).

**Comment by gmclelland** [comment]
FYI...I think this request sounds similar to https://github.com/processwire/processwire-requests/issues/215 in case you want to add a note there.

Thanks for sharing your suggested solution

**Comment by jmartsch** [comment]
Yes, this seems do be a duplicate of #215

**Comment by BitPoet** [comment]
Nope, the similarity in the issue titles is a bit misleading, #215 is about chunked network transfers. This one is about transferring the already uploaded file from memory to the disk. I'll try and find a better title :-)

A chunked upload implementation will avoid the problem as it will implement its own routine for writing the target file, but as long as it isn't there as PW's default and sure to work under any circumstances, I believe my solution will still have value.

**Comment by gmclelland** [comment]
Thanks for the clarification

**Comment by BitPoet** [comment]
No problem :-) I changed the title to avoid confusion. It really looked quite similar at first glance.

**Comment by ryancramerdesign** [comment]
Thanks, this seems like a good idea. Thanks for the suggested code, this helps a lot, I have added it.

**Comment by BitPoet** [comment]
Brilliant, thank you for the quick adaption!
