### ISSUE TITLE
add hook to getPrimaryNavArray

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-requests#238]
### Short description of the enhancement
With this modification one can disable the page tree navigation item completely for speficic roles or users, not just hide it via JavaScript and CSS.

This was asked many times in the forum like [here ](https://processwire.com/talk/topic/6142-hide-page-tree-in-the-admin/) or [here ](https://processwire.com/talk/topic/18445-change-default-admin-page-loaded-hide-pages-tree/) or [here](https://processwire.com/talk/topic/15981-hide-tree-dropdown-menu/), and we have no working solution for AdminThemeUikit right now.

With this modification we can use a hook to modify what is shown in the top navigation. For example:
```
$this->addHookAfter('AdminThemeUikit::getPrimaryNavArray', function (HookEvent $event){
      if($this->user->hasPermission('view-pagetree') || $this->user->isSuperuser()) return;
      $items = $event->return;
      foreach($items as $key => $value){
        if($value["id"] == 3){
          unset($items[$key]);
        }
      }
      $event->return = $items;
    });
```
hides the "pages" navigation item for all users that don't have the "view-pagetree" permission.

### Why would the enhancement be useful to users?

Some programmers like me or Bernhard use ProcessWire as a Framework to develop custom backends with custom dashboards for customers. Too not confuse a normal user (non-superUser) it is a good thing to remove options that they don't need.

My first page for example is a ListerPro and I don't want normal users to see the structure behind the scenes, so I want to disable the "pages" menu in the top bar (I don't use sidebars).

### Optional: Screenshots/Links that demonstrate the enhancement

Your screenshots/links go here.
![image](https://user-images.githubusercontent.com/551551/47375854-844e8180-d6f1-11e8-8518-89595d4bc941.png)

### Create custom navigation
It would even be better, if we could create the top navigation by ourself, like with MarkupNavigation module. But thats a different story.

### Pull request
I will open a pull request for this feature

**Comment by jmartsch** [comment]
Actually,﻿ there is a working module to hide the "page" item from the navigation and also redirect users to another page instead http://modules﻿.processwire.com/modules/admin-restrict-page-tree/
However, I think this PR would still be a good thing.

**Comment by matjazpotocnik** [comment]
@jmartsch, AdminThemeUikit::getPrimaryNavArray is now hookable so that this feature request can be closed now?
