### ISSUE TITLE
Allow use of custom classes for Repeater Pages

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-requests#239]
### Short description of the enhancement

I would like to be able to use a custom class (extending RepeaterPage) to represent repeater pages that use a particular template.

### Current vs. suggested behavior

Right now if you try to enter a custom class in the repeater's template settings, ProcessWire silently overwrites it with "RepeaterPage".

In an earlier version of PW I was able to get around this by adding the following to my site/ready.php file:
```
$t = $templates->get('repeater_template_name');
$t->pageClass = 'MyCustomClassName';
```
With the latest version of PW (3.0.98) there is an additional check in FieldtypeRepeater.module (line 745) which enforces the RepeaterPage class and renders my attempts impotent.

Edit: The spot to change (PW 3.0.229) is now line 909:

```
// load the repeater pages
		$options = array(
			'cache' => false, 
			'caller' => $this->className() . '::wakeupValue',
			'loadOptions' => array(
				'cache' => false, 
				'parent_id' => $parent_id, 
				'template' => $template,
				//'pageClass' => $this->getPageClass(), // MOD - This was preventing us from extending repeater pages using a custom class				
				'pageArray' => $pageArray, 
			)
		);
```

Edit 2: I discovered that Lines 242-247 must also be commented out now or else this will only work for Superusers.

I hacked the core and removed this line to get it working in my application, with no apparent side effects. It seems like this line should be removed and a check should be put in place to simply ensure that the class used extends RepeaterPage, rather than preventing the use of any other class altogether.

### Why would the enhancement be useful to users?

When using PW as a web app framework, the ability to extend the Page class is a must for keeping code clean and organized. Sometimes you also want to be able to extend the functionality of a repeater page.

**Comment by WebWorkingMan** [comment]
[I'd run into the same problem](https://processwire.com/talk/topic/26602-how-do-you-implement-custom-page-classes/?do=findComment&comment=226742) and didn't find a solution for extending a repeater class.

In order to keep my code as clean as possible it would be nice to have this opportunity.

**Comment by elabx** [comment]
As @WebWorkingMan mentions, this would be great for keeping the house clean.  RepeaterPage and RepeaterPageMatrix are  on my daily usage since I treat them as components that build the pages so extending them with custom classes would be really nice.

I think the usage of Repeaters/RepetearMatrix for "page building" is common so this might be a feature a lot of developers could benefit from.

**Comment by jlahijani** [comment]
@ryancramerdesign Any way to prioritize this one considering it's 5 years old and used by those of us with advanced use cases (ie web-app development)?

**Comment by ryancramerdesign** [comment]
@thetuningspoon @jlahijani @elabx @WebWorkingMan I have added this but in a different way than shown above. I thought the method discussed here could be potentially problematic when it came to fields that extend RepeaterPage, such as FieldsetPage and RepeaterMatrixPage, so opted for a a more direct solution that uses the same scheme used for other custom page classes. If you've got a repeater field named "my_items" then you'd create this file and class:

/site/classes/MyItemsRepeaterPage.php
~~~~~
<?php namespace ProcessWire;
class MyItemsRepeaterPage extends RepeaterPage {
  // loaded method for demonstration purposes only (feel free to remove)
  public funtion ___loaded() {
    $this->message("Loaded custom class for repeater page $this->id"); 
  }
}
~~~~~
Or if you want to use something else, you might do it during init() or ready(): 
~~~~~
<?php namespace ProcessWire;
class MyCustomClass extends RepeaterPage {}
$field = wire()->fields->get('my_items');
$field->type->setCustomPageClass($field,  'MyCustomClass'); 
~~~~~

**Comment by thetuningspoon** [comment]
Sounds good. Thanks Ryan!
