### ISSUE TITLE
URL fields link abstraction

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-requests#24]
PW3 added link abstraction to text areas https://processwire.com/blog/posts/processwire-3.0.6-brings-pages-upgrades-and-link-abstraction/#new-link-abstraction-features.

Can we also have that for URL fields?

Note: this would only affect internal links in URL fields.
### Current vs. suggested behavior

Currently links to internal pages in URL fields would break if a page is moved.  If the url fields had link abstraction, pages could be moved without worrying about the values in URL fields breaking.

**Comment by Toutouwai** [comment]
You can install the [Page Path History](http://modules.processwire.com/modules/page-path-history/) module and if paths change, links coming from anywhere (inside or outside of PW) will redirect to the new path.

**Comment by gmclelland** [comment]
Indeed, that might be the best option.  I'll go ahead and close this.  If anyone else has any ideas feel free to reopen.
