### ISSUE TITLE
Expose actual user and role/s through ProcessWire.config object

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-requests#241]
### Short description of the enhancement
Expose the actual user and his role/s through the ProcessWire.config object so we can use them in JavaScript to trigger actions just for specific users or roles in the admin (frontend would be nice too).

Right now the actual user and roles are assigned as a classname to the body element (user-username)

### Why would the enhancement be useful to users?
I think this could be useful for many use cases like my request #236 or for AdminOnSteroids, because we can select which scripts are executed for which role or user.

**Comment by ryancramerdesign** [comment]
Thanks @jmartsch I have added this.
