### ISSUE TITLE
Open collapsed File/Image/CKEditor fields if a file is dragged to them

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#242]
### Short description of the enhancement

I often set File and Image fields to appear collapsed when empty. But when dragging one or more files/images to them it's annoying when I realise I forgot to open the collapsed field first.

This request is that collapsed File, Image and CKEditor fields open when a file is dragged over them.

How this could be done...

```js
$(document).on('dragenter', '.InputfieldImage.InputfieldStateCollapsed, .InputfieldFile.InputfieldStateCollapsed, .InputfieldCKEditor.InputfieldStateCollapsed', function(e) {
    var dt = e.originalEvent.dataTransfer;
    if(dt.types && (dt.types.indexOf ? dt.types.indexOf('Files') !== -1 : dt.types.contains('Files'))) {
        InputfieldToggle($(this), true);
    }
});
```

![drag](https://user-images.githubusercontent.com/1538852/47977375-96cab100-e11c-11e8-85de-d9d8e70b0af1.gif)

**Comment by ryancramerdesign** [comment]
@Toutouwai That's a really great idea — I have added this, thanks!

**Comment by Toutouwai** [comment]
Thanks.
