### ISSUE TITLE
Rename repeater template and parent when changing repeater field name

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#27]
### Short description of the enhancement

The repeater template and its Admin > Repeaters parent should be renamed to match the new field name.
### Current vs. suggested behavior

The current behavior results in repeater templates named the same as the original repeater field, and its parent page also with the original field name, eg. Admin > Repeaters > original_field_name
### Why would the enhancement be useful to users?

I think it's one of those consistency things that should be cleaned up. It could also be quite useful if you end up with a corrupted db and need to manually cleanup a repeater field and its template and parent page.

**Comment by Toutouwai** [comment]
This seems to be implemented now. When I rename a repeater field in PW 3.0.235 the associated template and parent page under the Admin branch are automatically renamed.

**Comment by adrianbj** [comment]
Looks good to me now too. Thanks for the heads up.
