### ISSUE TITLE
Add autocomplete to URL fields

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-requests#28]
### Short description of the enhancement

I think it would be helpful to add a page autocomplete to URL fields.

**Comment by adrianbj** [comment]
Not saying it shouldn't be in the core, but does this module suit your needs:
https://processwire.com/talk/topic/10530-module-fieldtypeassistedurl/?do=findComment&comment=99531

**Comment by Toutouwai** [comment]
@gmclelland , are you thinking of URLs to internal pages?

Because I don't see how PW could predict an external URL. And for internal URLs you're better off using a 'single' Page field and outputting the url with `my_page_field->url`

**Comment by gmclelland** [comment]
I didn't know about that module.  It wasn't listed in the directory, but it does work.  It autocompletes the page names and It evens provides a way to drill down and select from the page tree.  It also works the latest version of Processwire 3.0.36.

**Comment by gmclelland** [comment]
Yes, I was referring to autocompleting internal pages only.

**Comment by isellsoap** [comment]
@gmclelland So this issue can be closed?

**Comment by gmclelland** [comment]
Yes, I would say http://modules.processwire.com/modules/fieldtype-assisted-url/ almost covers everything.  Earlier I was wrong when I said it wasn't in the modules directory.

Maybe one day it could be included in Processwire core?

Thanks to @rolandtoth, it is also working with https://github.com/rolandtoth/AdminOnSteroids -- InputfieldURLChecker module
