### ISSUE TITLE
Rough admin rendering of PageTable when "page-view" permission only

### ISSUE THREAD

**Issue by er314** [processwire/processwire-requests#284]
### Short description of the enhancement

When "page-view" only permission on field of type PageTable,

- Current behaviour : in the admin, the rendering of the field only displays the page IDs of the items  (ex : "1234|1235|1236")
		-> this is rather rough ! :-)

- Expected behaviour : display the table/matrix view, as defined in the field's "Input" settings, similarly to the display when "page-edit" permission is set, except that here there should not be any clickable link towards the target pages (well, I guess)

Additional point : when "page-edit" permission is also set, but "page-delete" sub-permission is NOT set, then anyway the entries of the pageTable can be removed, with the trashcan icon located in the matrix view. Well, they are not actually deleted, they are removed/disassociated from the PageTable (and can later be added to it again).
Is this the intended behaviour ?
Wouldn't it be more relevant and more clear, that, when there's no "page-delete" permission for a PageTable, BOTH delete AND removal/disassociation would be denied ? (+ the trash icon wouldn't show)

PW 3.0.127

**Comment by jmartsch** [comment]
@er314 Could you mayme provide a screenshot?

**Comment by er314** [comment]
Sure, here it is : 
- 1st screenshot is the display of a PageTable field, where "view" + "edit" permissions are enabled on this field for the target user role : 
_(note that this role doesn't have any "page-delete" permissions whatsoever on any associated templates)_

![pagetable-with-edit-perm](https://user-images.githubusercontent.com/8220747/54455429-0ea88800-475c-11e9-945b-ac861dc26140.png)

- 2nd screenshot is after disabling "edit" permission on this field for the target user role : 
(note : "view" permission is still set, + the access toggle _"Show field in page editor if viewable but not editable (user can see but not change)"_ is also checked)

![pagetable-without-edit-perm](https://user-images.githubusercontent.com/8220747/54455443-1536ff80-475c-11e9-8a4b-0466554d5bff.png)

**Comment by matjazpotocnik** [comment]
That's because renderValue() method is missing in InputfieldPagetable.module. It's on Ryans's todo list for some time...

**Comment by er314** [comment]
Solved as per issue #1274
