### ISSUE TITLE
cloning templates and field overrides

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-requests#3]
Copied over on request from 
https://github.com/ryancramerdesign/ProcessWire/issues/1230#issuecomment-249245448

Not sure this has been mentioned before:
If I clone a template, the field overrides (labels, look and behavior) set in the source template get all lost in the template clone, so it is not a real clone. It can be a source for errors if I forget to fix the fields and it is a bit tedious to go through all the fields to update them manually sometimes.

**Comment by ryancramerdesign** [comment]
The context settings actually aren't part of the template, which is why they don't get cloned. I can look to see what's possible here though.

**Comment by teppokoivula** [comment]
Definitely a +1 for this request. Without overrides the cloned template is only halfway there. If the intention is to set up a similar setup elsewhere, this can often mean a lot of manual work.

**Comment by matjazpotocnik** [comment]
+1

**Comment by adrianbj** [comment]
Not really sure why I am sharing this, but Migrator actually handles these template context settings when it migrates a field from site to site. Here is the approach I took:

https://github.com/adrianbj/ProcessMigrator/blob/master/ProcessMigrator.module#L2104-L2109
and
https://github.com/adrianbj/ProcessMigrator/blob/master/ProcessMigrator.module#L1323-L1335

Maybe it will give you a quick insight into what is required, although I am sure you already know :)

**Comment by isellsoap** [comment]
@matjazpotocnik Please use GitHub’s built-in comment emojis and remove your comment. Comments consisting solely of the string "+1" just clutter the feature request thread. I added a respective note to the README.md of this repository. Thank you.

**Comment by tbba** [comment]
too old

**Comment by adrianbj** [comment]
Why does the age of an issue affect its relevance?

Please consider reopening as I think this is something that is important.

**Comment by Toutouwai** [comment]
I agree with Adrian - please reopen.

This issue is definitely solvable because I do so in my Add Template Enhancements module: https://modules.processwire.com/modules/add-template-enhancements/
Would be great to have this solved in the core though.
