### ISSUE TITLE
Add arrayColumn() method to WireArray API

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-requests#30]
### Add arrayColumn() method to wire array API

I sometimes find PHP's [arrayColumn()](https://secure.php.net/manual/en/function.array-column.php) function useful and I extend WireArray with it using a hook. Could it be added to the core class?

Here's the code I use to add the arrayColumn() function.

```
/**
 * Extend WireArray to allow the fetching of all field values of a given name.
 * Designed to be similar to PHP's arrayColumn()
 */
$pages->addHook('WireArray::arrayColumn', function($event) {
    $column = $event->arguments(0);
    if (empty($column)) $column = 'title';
    $result = array();
    foreach ($event->object as $s) {
        $result[] = $s->$column;
    }
    $event->return = $result;
});
```
### Current vs. suggested behavior

Current behaviour is fine but requires the use of hook extension of the base class.
### Why would the enhancement be useful to users?

Would allow pulling a column of values from wire array results without having to use a custom hook. 

```
$related_names = $repeater->people->arrayColumn();
```

**Comment by LostKobrakai** [comment]
Isn't that what `$repeater->people->explode('title')` does?

**Comment by netcarver** [comment]
@LostKobrakai - thank-you, I wasn't aware of that. Despite looking through the cheatsheet I have missed it all this time. Switching over to it and closing this issue.

**Comment by adrianbj** [comment]
@netcarver - take a look at this post which introduces `explode()` and some other handy tools:
https://processwire.com/talk/topic/5098-new-wirearray-api-additions-on-dev/

**Comment by adrianbj** [comment]
PS I actually use it all the time in the Tracy console for testing selectors

```
d($pages->find("template=basic-page")->explode('name'));
```

**Comment by teppokoivula** [comment]
Slightly off-topic, but  as a name WireArray::arrayColumn() would've made so much more sense. Never really got the naming of WireArray::explode() :)
