### ISSUE TITLE
"Add Existing" (Page Reference) option for Repeaters?

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#307]
Just thinking out loud here...

With repeaters, you can add new items (the items are ultimately stored as pages).

With page fields, you can add existing items (pages).

What if it were possible to add **pages** (single reference) as a repeater item, directly?

An indirect approach of doing this currently with Repeaters would be to just have a page reference field on each added repeater item, but this requires you to have a repeater item to begin with.

Another indirect approach of doing this is to use RepeaterMatrix and just split them up into 2 different types.

What I'm thinking about is the ability to add a page item (single reference) directly to the repeater.  It's like Repeaters with page support, if that makes sense.

**Comment by teppokoivula** [comment]
Just to clarify: are you thinking of just adding non-repeater items to a repeater page array so that they become visible (as non-editable items with the "item header" row only), or also making them editable just like "regular" repeater items? :)

**Comment by jlahijani** [comment]
The more I think about this, the less it makes sense now.  Repeaters are based on consistency of fields for each repeater item, so what I proposed doesn't follow that rule.
