### ISSUE TITLE
Make page meta searchable in pw selectors

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-requests#312]
The new $page->meta() feature in 3.0.133 is nice. It would be even great to make this data usable in pw query selectors.

I have a use case, where I want to show only a field in the admin panel when some meta data is set to a page.

e.g.
![image](https://user-images.githubusercontent.com/488163/60088373-d6dbb400-973e-11e9-8f82-40fd0b2f5274.png)

**Comment by teppokoivula** [comment]
ShowIf conditions are evaluated in the front-end of the Admin, so this would also require the meta to be fully available in the source of the page. Your use case is interesting, but at the same time this would make the meta feature less useful for other purposes – personally I don't think that it's worth it, but of course the decision is up to Ryan :)

Note: this isn't _directly_ related to selectors. The syntax used by field dependencies is pretty much the same as with "real" selectors, but they are not routed through the (backend) selector engine.

**Comment by Toutouwai** [comment]
@tiefenb, because a page's meta values cannot change on the fly during page edit (well, not unless you are doing some custom AJAX to deliberately change them) you don't really need the JS processing that the core offers in the showIf/requiredIf dependency feature.

Instead you can remove a field from Page Edit if some meta value is not set, which would have the same effect as a showIf dependency. For example:

```php
$wire->addHookAfter('ProcessPageEdit::buildFormContent', function(HookEvent $event) {
    /* @var InputfieldWrapper $wrapper */
    $wrapper = $event->return;
    $f = $wrapper->getChildByName('your_field');
    if(!$f) return;
    /* @var Page $page */
    $page = $event->object->getPage();
    if($page->meta('out_of_stock') !== 1) $wrapper->remove($f);
});
```

**Comment by tiefenb** [comment]
makes sense - I solved this that I show this field always. it's only a output of some information with MarkupRuntime and within the field I print the meta data. if no meta data is set I will show the field too but make an other output message.
