### ISSUE TITLE
Open and focus inputfield according to GET parameter

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#315]
### Short description of the enhancement

Now that we have the `InputfieldFocus()` function in `inputfields.js` it would be a nice enhancement if we could specify an inputfield ID to open and focus as part of the URL.

Examples:
```
/processwire/page/edit/?id=1&focus=Inputfield_headline
/processwire/setup/field/edit?id=117&focus=Inputfield_minlength
```

**Comment by jmartsch** [comment]
Duplicate of https://github.com/processwire/processwire-requests/issues/236
