### ISSUE TITLE
Modules Directory JSON web service: Remove query limit

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-requests#319]
Right now we can only query a maximum of 400 modules at once (https://modules.processwire.com/export-json/?apikey=pw223&limit=400). As I am developing a new [module manager/installer](https://processwire.com/talk/topic/20649-revamped-modules-install-interface/?do=findComment&comment=178860) I want to get the information of all modules, and have to request them in batches which is very cumbersome.

Please enable it to get all modules at once, which should be the default if no limit is specified, IMHO.

**Comment by LostKobrakai** [comment]
I'm not sure this is a good idea. Limiting the number of results is an important part of keeping memory and computational resource consumption in check and batching/paginating lists is the common way to let people access data via APIs. Cumbersome or not, it's how things should be done.

**Comment by jmartsch** [comment]
This could be overcome if a static file or cached result would be generated as soon as a module changes. Then we could query this file. In addition my request #320 when the last update happened would enable us to check if or not to download the module list.

**Comment by LostKobrakai** [comment]
I've no idea about the possible parameters for this API, but usually it's not only about having a single complete list, but searches or filtering result in arbitrary amounts of result-sets. Sure things can be cached, but that only works if you either accept the full load when a cache doesn't exist or you'e able to generate all possible caches you need when an update happens. 

If it's just a single list of things I'm not sure if an API is the way to go and not just store a file somewhere on S3 with all the information and let that be accessed. Etags would even come for free that way, so you can use a HEAD request to see if the file changed or not. This is what I do here: https://bobs-list.kobrakai.de/ based on https://repo.hex.pm/builds/elixir/builds.txt.

**Comment by jmartsch** [comment]
I am going to agree with @LostKobrakai that this maybe isn't a good idea. I created a new request to generate a static file. #330
