### ISSUE TITLE
Please add support for additional file extensions in ProcessLanguageTranslator

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-requests#329]
### Short description of the enhancement

Currently the possible extensions in ProcessLanguageTranslator are hard coded. I'm developing a module that loads data from different files having different file extensions (PHP, JS, CSS, READY, HOOKS). READY and HOOKS files are also PHP files but they need to have a different file extension for the module to work.

### Current vs. suggested behavior

Currently .ready and .hooks files are not scanned for translatable strings

### Why would the enhancement be useful to users?

It would add full multilanguage support to RockMarkup Inputfields (and all modules that are based on it, like RockTabulator...): https://processwire.com/talk/topic/21982-rockmarkup-inputfield-to-easily-include-any-phphtmljscss-in-the-pw-admin/

### Optional: Screenshots/Links that demonstrate the enhancement

Here are the simple changes that would be necessary: https://www.diffchecker.com/h0coD50D

I can then add those extensions easily in my module:

```php
      // add language support for .ready and .hooks files
      $this->addHookAfter("ProcessLanguageTranslator::getExtensions", function($event) {
        $event->return = array_merge($event->return, ['ready', 'hooks']);
      });
```

And those files show up properly in the list:

![img](https://i.imgur.com/80EGQma.png)

Thank you!

**Comment by jmartsch** [comment]
I would recommend adding a .php extension to the .ready file, so it reads myfile.ready.php, as it is also PHP, and with the PHP extension a IDE would also provide the correct syntax highlighting, which isn't the case if you use .ready as an extension.

Also an extension like .ready could be a security risk, as the server doesn't parse it, but instead delivers it as plain text to the browser. If you had critical information in these files, this would be bad.

**Comment by BernhardBaumrock** [comment]
Thx,
I know that I could do that, but that would break my module because - as I said - it relies on the diffent file name extensions. That's because of how I'm using $files->find() to find the correct files (using ['extensions' => ['ready']).
Not sure about the security risk though. Maybe it would make sense to implement that extra step to have those files calles ready.php and hooks.php
I'm closing this issue since I've implemented direct links to file translations in my GUI

**Comment by BernhardBaumrock** [comment]
@jmartsch what about .module files? They are also no .php files and used in the core... I guess it should be fine, but I'll ask in the security board :) https://processwire.com/talk/topic/22232-security-risk-to-use-custom-file-extensions/

**Comment by jmartsch** [comment]
Same thing that I wrote applies to the .module files. But access to those files is restricted/blocked by the .htaccess file, so security is only a concern if the .htaccess file isn't being used and you don't extend it with your .ready and .hook file extensions.
The following line has to be changed for this:
`RewriteCond %{REQUEST_URI} (^|/)(site|site-[^/]+)/modules/.*\.(php|inc|tpl|module|info\.json)$ [OR]`

Regarding the .module file extension: This is something that also annoys me but you also can add a .php behind the .module extension, which Adrian already does with his TracyDebguger module.

**Comment by teppokoivula** [comment]
Hey @BernhardBaumrock! Just for the record I opened an issue regarding these files and their potential problems earlier: https://github.com/BernhardBaumrock/RockMarkup2/issues/2.

I'll have to agree with @jmartsch that renaming them to something else (with .php extension) would be a very good idea. Either that, or you could add custom .htaccess files to protect them from direct access (as outlined above.) You could distribute such a file with your module, but again: it's still not quite as good as using a .php extension :)

One thing to add regarding .module files is that in some ways they're a thing of the past. Most devs seem to use .module.php these days, and if you look at Ryan's recent modules those also make use of this pattern. So yes, exactly as @jmartsch pointed out above these files are protected by default ProcessWire .htaccess rules, but they're also kind of an antipattern these days (imho).
