### ISSUE TITLE
htaccess directives for WordPress hackbots

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#333]
Many hackbots (presumably) seem to be accessing urls like the following which show up in my 404 error log:
```
/wp-login.php
/wp-includes/wlwmanifest.xml
/blog/wp-includes/wlwmanifest.xml
/wordpress/wp-includes/wlwmanifest.xml
/wp/wp-includes/wlwmanifest.xml
/site/wp-includes/wlwmanifest.xml
```

What are you thoughts on having a section in PW's htaccess file (perhaps disabled by default) to easily and conveniently handle those in a recommended way?

**Comment by lesaff** [comment]
I like this suggestion. Those are pretty common 404 errors that should be added to any CMS not named Wordpress.

Might I also suggest adding this as well? 

```
/autodiscover/autodiscover.xml
```

**Comment by jlahijani** [comment]
Perhaps it's better leaving them out and doing it manually.

Resources
https://processwire.com/store/pro-dev-tools/wire-request-blocker/#url-strings-to-trigger-a-strike
https://processwire.com/store/pro-dev-tools/wire-request-blocker/#blocking-requests-from-your-htaccess-file
