### ISSUE TITLE
New visibility option for Open and Locked

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#346]
### Short description of the enhancement

It would be great to have an always open & locked option

### Current vs. suggested behavior

Currently if you want locked (not editable), it needs to be collapsed when blank and open when populated, but this is not that useful for checkbox fields.

### Why would the enhancement be useful to users?

As an example, I have a checkbox field that indicates the confirmed status of a user:

![image](https://user-images.githubusercontent.com/871211/69274114-89992c80-0b8e-11ea-973e-b54f6704346c.png)

The problem is that it's not ideal to not be able to actually see if the checkbox is checked or not without opening the field:

![image](https://user-images.githubusercontent.com/871211/69274185-b0576300-0b8e-11ea-9cbc-dc62a7056a5b.png)

I am sure there are plenty of other uses as well.

Thanks for considering.

**Comment by adrianbj** [comment]
Thinking about this further, I actually think open/closed/AJAX loaded should be one setting, and locked (not editable) should be a completely different setting so we can define the exact combination we want.

**Comment by teppokoivula** [comment]
> [...] I actually think open/closed/AJAX loaded should be one setting, and locked (not editable) should be a completely different setting [...]

Backward compatibility concerns aside, I'm going to agree with this — we've got quite a few combinations already, and regardless I've been running into situations that are not supported. 

Case in point, I ran into exactly the situation mentioned in this request a while ago.

**Comment by BernhardBaumrock** [comment]
Agreed. Same here! That is one of the rare cases where PW is not really clever and future-proof. Though one can fortunately define the collapsed state via hook on buildForm() so we actually already have unlimited options :)

**Comment by ethanbeyer** [comment]
I love the idea of keeping those flags separate. Would make for a lot more flexibility and fewer things to read through in order to determine which option it is you want.

**Comment by Jonatan-r** [comment]
I really vote for this as well!!

([https://processwire.com/talk/topic/23307-show-data-in-locked-custom-field-–-locked-field-not-showing/?tab=comments#comment-199083](https://processwire.com/talk/topic/23307-show-data-in-locked-custom-field-–-locked-field-not-showing/?tab=comments#comment-199083))

Would be very useful to have :)

**Comment by adrianbj** [comment]
Just another bump for this. Today I wanted to have a non-editable field closed and AJAX open. The field contains raw text extracted automatically from the uploaded PDF. This is very long, so I would like to prevent it being loaded on every page edit load, but I also don't want it to be manually editable - a combo which isn't currently possible.

On a slight related topic, it would be good to have the option for non-editable textarea fields to have a fixed height with internal scroll. In my example above, the output is very long and makes for a lot of scrolling on the entire page.

**Comment by BernhardBaumrock** [comment]
+1 for splitting this into <s>two</s> **three** settings

For backwards compatibility I think it should not be too tricky to keep the old constants and if an old constant is used simply set the new settings accordingly. I thought about it a little bit and think I found a good concept!

```php
// define field's collapsed state
// $field->set('collapse', Inputfield::collapseNever);
const collapseNo = 0;
const collapseYes = 1;
const collapseBlank = 2;
const collapseHidden = 4;
const collapsePopulated = 5;
const collapseNever = 9;

// define if field is loaded via ajax or not
// $field->set('ajax', Inputfield::ajaxPopulated);
const ajaxNo = 0;
const ajaxYes = 1;
const ajaxBlank = 2;
const ajaxPopulated = 5;

// define the locked/unlocked state of the field
const lockNo = 0;
const lockYes = 1;
const lockPopulated = 5;
```

This could mean that we could keep the old settings (and do not break any sites):

```php
$field->set('collapsed', Inputfield::collapsedBlankAjax);
```

Which would translate to

```php
$field->set('collapse', Inputfield::collapseBlank);
$field->set('ajax', Inputfield::ajaxYes);
```

And could even be extended to this (which is currently not possible)

```php
$field->set('collapse', Inputfield::collapseBlank);
$field->set('ajax', Inputfield::ajaxYes);
$field->set('lock', Inputfield::lockYes);
```

The concept would also introduce a new feature that I've realized with hooks in the past: Having a field that is editable when blank but locked when populated (for one time input):

```php
$field->set('lock', Inputfield::lockPopulated);
```

And last but not least it would perfectly support @adrianbj s example:

> Today I wanted to have a non-editable field closed and AJAX open.

```php
$field->set('lock', Inputfield::lockYes);
$field->set('collapse', Inputfield::collapseYes);
$field->set('ajax', Inputfield::ajaxYes);
```

I think this would be an important fix/addition for/to PW! 😎

Edit: Changed `locked` property to `lock` to make it align with `collapse` vs the old `collapsed` and to avoid confusion when to use what.

```
old = collapsed
new = collapse, lock and ajax
```

**Comment by ryancramerdesign** [comment]
@adrianbj Thanks, I have added this.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - will be a very useful improvement!
