### ISSUE TITLE
Advanced Selector Operator: ^!=

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#352]
ProcessWire has this selector operator:
```
^=  Contains the exact word or phrase at the beginning of the field
```

I ran into a situation where I had to find pages that DO NOT begin with a specific string, which is not an operator in the selector operators documentation.  Therefore, an operator like ```^!=``` could be useful.

**Comment by Toutouwai** [comment]
Did you try negating the whole selector clause?

```php
$results = $pages->find("template=foo, !your_field^=bar");
```

**Comment by jlahijani** [comment]
I will look into that.  Forgot / didn't know you can do it that way.  Closing.
