### ISSUE TITLE
Support for Select Options as a custom field for images

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#355]
### Short description of the enhancement

Support for Select Options as a custom field for images as per https://processwire.com/blog/posts/pw-3.0.142/#custom-fields-for-files-images

### Why would the enhancement be useful to users?

Creating a Page Reference field seems cumbersome for simple select options like left, right, full alignment

**Comment by Toutouwai** [comment]
Dup of https://github.com/processwire/processwire-requests/issues/353
