### ISSUE TITLE
useNavJSON for top level menu items

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#361]
### Short description of the enhancement

Currently if you create a Process module and you set its parent to the main Admin page (ID = 2) so that it appears as a top level menu item, you can't make use of the `executeNavJSON()` method to dynamically set the subitems. 

### Why would the enhancement be useful to users?

There are lots of use cases where you want to be able to dynamically define the subitems (and especially something like a counter after each item). 

Yes, I could move the page under Setup or some other parent to get it working, but I really want this to be a top level menu item and I don't think the position of it should affect the ability to use this type of submenu generation.

**Comment by BernhardBaumrock** [comment]
This would be great! +1

**Comment by Toutouwai** [comment]
Similar request: https://github.com/processwire/processwire-requests/issues/189

**Comment by adrianbj** [comment]
Thank @Toutouwai - sorry I missed that one - I'll add my support to this over there and close this.
