### ISSUE TITLE
GUI for Page Path History

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-requests#38]
### Short description of the enhancement

Add an admin interface to manage redirects, made by Page Path History. 
### Why would the enhancement be useful to users?

Something alike [already exists](https://processwire.com/talk/topic/9436-page-path-history-manager/), but I think the core module is incomplete without such interface. There is actually no way to control these redirects. And lots of redirects is not a good thing.

**Comment by teppokoivula** [comment]
While I agree that in some cases such a feature would be nice, on the other hand I must say that I've never really felt a need for it myself. Part of the beauty of Page Path History is exactly in it's automatic, behind-the-scenes nature. I'm wondering whether this really needs to be in the core? 

Considering that there's already a third party module that does a good job on it's own, I'd be tempted to say that this would mainly be an unnecessary complication.

**Comment by ivangretsky** [comment]
Thanks for reply, Teppo!

1) On the subject. Without such a feature I got data in my site I can only add to, but not revise or even just flush without going to db management tool. This does not seen right and could potentially lead to bugs that are almost no way debuggable. 

2) On the process. I do not understand what your answer means to me and to the future of request. Is this your private opinion, or do I have to convince you to get this issue further)) I am talking not so much about this specific issue, but in general. As I tend to receive answers not from Ryan here, this becomes more and more vague. I think the answer to this can become a nice topic for your weekly issue.

**Comment by teppokoivula** [comment]
1) One solution that comes to mind (and doesn't require a full-blown management tool) would be an option of clearing data cached by Page Path History. Similar to what Page Render provides, i.e. a checkbox in the module settings. Seems to me that this would already help quite a bit, without being excessively complex.

2) It's just my opinion, nothing more. Ryan has the final say on anything and everything related to ProcessWire's code base, that hasn't changed. The best I (or anyone else here) can really do is provide some additional insight on the topics being discussed :)

**Comment by teppokoivula** [comment]
Created a pull request with the change I've suggested here, i.e. a very simple GUI that basically does two things: displays the amount of stored page paths, and makes it possible to clear all of them via the module config. Let's see what @ryancramerdesign thinks of this approach.

@ivangretsky, I'm aware that this is not exactly what you were suggesting, but personally I think this would uphold a proper balance between "having nice features" and "keeping it simple" :)

**Comment by ivangretsky** [comment]
I guess your answer to No. 2) is actually not correct. If you know how to ask and who to ask you will get a pull request to fix your issue)) Thanks, man!

I will still wait a day before closing this one - maybe Ryan will implement a full-fledged redirect management GUI while working on your pull request))

**Comment by teppokoivula** [comment]
Better leave this issue open either way, so that Ryan has time to properly evaluate the best solution. My pull request is just a suggestion, not sure what Ryan thinks of that :)

**Comment by teppokoivula** [comment]
@ryancramerdesign, just wondering if you could consider this as a potential addition to 3.1 – there's a PR with no conflicts, and as far as I can tell, this should be a pretty harmless thing to add. Also it would improve the consistency of cache management in ProcessWire.

**Comment by horst-n** [comment]
An additional point to this: As I really like the automatic-behind-the-scenes nature of the page path history module, I think it would be really helpful if the superuser gets some messages in cases where a really huge amount of redirects are created for a single page.

**Comment by ivangretsky** [comment]
Per page UI redirect management has been added as of [3.0.118](https://processwire.com/blog/posts/processwire-3.0.118-core-updates/#new-redirect-url-management-in-the-page-editor). It is not unified and probably not so easy to use when you got really lot of redirects/ I do not know if we should close this for now? What do you think @teppokoivula? Asking you cuz you made a PR)

**Comment by teppokoivula** [comment]
Just a quick heads-up that the PR for the simple cache clearing GUI is now merged to the dev branch :)
