### ISSUE TITLE
File/Image custom fields - support for CkEditor please.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#380]
### Short description of the enhancement

Hi @ryancramerdesign  - you mentioned in the initial blog post about this back in Oct 2019 that you thought you might be able to support CkEditor fields. I was hoping that maybe you had revisited this with the updates to this feature in 3.0.170, but I see it's still not available. 

This is a very important feature for image captions in the science world where we often need to italicize genus/species names.

Thanks for considering.

**Comment by Toutouwai** [comment]
This is implemented now (I checked in PW 3.0.235)

**Comment by adrianbj** [comment]
Thanks @Toutouwai - looks good here also.
