### ISSUE TITLE
Please sort pages in trash by their modified timestamp

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-requests#386]
### Short description of the enhancement

IMHO it would be great in many situations to list pages in the trash by their modified (trashed) date. The last page that was trashed should always appear on top of the list to make it easy to restore pages that where recently trashed.

### Current vs. suggested behavior

Currently the pages are sorted by... I don't know? It's always a mistery when I open the trash.

### Why would the enhancement be useful to users?

Recently a client called me: Bernhard, I deleted a project by accident. The project hat some related pages as well, so it was not easy to restore all pages from the list. I had to use Tracy Console and custom $pages->find() queries. If the pages where on top of the list it would just be clicks on the restore button...

Thx for considering!

**Comment by BernhardBaumrock** [comment]
```
    $this->addHookAfter("ProcessPageList::find", function($event) {
      $selector = $event->arguments(0);
      $page = $event->arguments(1);
      if($page->id !== $event->config->trashPageID) return;
      $event->return = $page->children($selector.",sort=-modified");
    });
```

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I have added this.

**Comment by BernhardBaumrock** [comment]
Great, thx :)
