### ISSUE TITLE
Better way to whitelist non-ascii characters (Asian characters) in config.php

### ISSUE THREAD

**Issue by gideonso** [processwire/processwire-requests#393]
For now, if a site needs non ascii page name, there are two setting needed to be set:

1. $config->pageNameCharset = "UTF8"
 
This is OK.

2. $config->pageNameWhitelist = "A very long Chinese Character List"

It is very hard to put all the Chinese character there. 

If there is another way to whitelist all the non-ascii character would be a big plus to ProcessWire multi-language support.

Related forum thread: https://processwire.com/talk/topic/12776-pw-3012-support-for-extended-utf8-page-namesurls/?page=2&tab=comments#comment-146652

**Comment by gideonso** [comment]
This can be done by leave $config->pageNameWhitelist = "". I close this request.

**Comment by openidauthority** [comment]
I propose that `$config->pageNameWhitelist = ""` _should_ disable the whitelist, and use only the internal blacklist.

To make this happen, another condition would need to be added to the sanitizer, right after checking the blacklist:

```
} else if($whitelist === false) {
  // whitelist is disable, allow everything that is not blacklisted
```
https://github.com/processwire/processwire/blob/master/wire/core/Sanitizer.php#L843

**Comment by ryancramerdesign** [comment]
@openidauthority Thanks, that makes sense to me, I have added it.

**Comment by matjazpotocnik** [comment]
@gideonso, can you close this issue if you are happy with Ryan's fix?

**Comment by gideonso** [comment]
It is good to me. Thanks a lot.
