### ISSUE TITLE
Add readme of module to module config screen

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-requests#399]
### Short description of the enhancement

I'm building a module that is configured mostly via code in config files. That means it is a little less user friendly than having a UI. So I decided to add the module's readme instead of config fields to the module's config screen:

![img](https://i.imgur.com/mgKWRkl.png)

Adding the readme is very simple and can be done using PW core tools:

```php
  /**
  * Config inputfields
  * @param InputfieldWrapper $inputfields
  */
  public function getModuleConfigInputfields($inputfields) {
    $readme = $this->wire->files->render(__DIR__."/README.md");
    $inputfields->add([
      'type' => 'markup',
      'label' => 'Readme',
      'icon' => 'life-ring',
      'collapsed' => Inputfield::collapsedYesAjax,
      'value' => $this->wire->sanitizer->entitiesMarkdown($readme, true),
    ]);
    return $inputfields;
  }
```

### Why would the enhancement be useful to users?

As this is really easy to do and turned out to be very helpful I thought: Why not add the readme of the module by default if one exists?

**Comment by jmartsch** [comment]
Great idea.

**Comment by adrianbj** [comment]
@BernhardBaumrock - have you used @netcarver 's ModuleReleaseNotes ? It adds that, as well as changelog and license files, all nicely collapsed under Support Files:

![image](https://user-images.githubusercontent.com/871211/115147606-ac907000-a010-11eb-8452-1b585c68b73d.png)

**Comment by jmartsch** [comment]
> @BernhardBaumrock - have you used @netcarver 's ModuleReleaseNotes ? It adds that, as well as changelog and license files, all nicely collapsed under Support Files:
> 
> ![image](https://user-images.githubusercontent.com/871211/115147606-ac907000-a010-11eb-8452-1b585c68b73d.png)

Yeah, I remembered that also.

**Comment by BernhardBaumrock** [comment]
Thx adrian, totally forgot about that module :)
