### ISSUE TITLE
Allow whitespace in passwords 

### ISSUE THREAD

**Issue by gRegorLove** [processwire/processwire-requests#4]
I was surprised to learn that InputFieldPassword does not allow whitespace*. I'd strongly recommend allowing them since I'm not aware of any technical reasons for the restriction.

\* My PW password has had whitespace for a while, so at first I thought maybe the code changed. Then I remembered I had forgotten my password and reset it via the API, which doesn't have the whitespace restriction. Only today did I go in to change a password via the admin. :]

**Comment by ryancramerdesign** [comment]
We already do support whitespace in passwords (PW 3.x and 2.8.x). Where specifically is it not allowing whitespace? and can you give me an example of a password that doesn't work (not a real one of course).

**Comment by gRegorLove** [comment]
It's in the admin > select profile > update password. 

This is on PW 2.7.2, which I realize is older. I checked [this line](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Inputfield/InputfieldPassword.module#L90) of InputFieldPassword.module in master and dev branch and it seems to still restrict the password. Am I looking in the wrong branch/tag?

**Comment by ryancramerdesign** [comment]
This was added in pw 3 and 2.8 so you won't see it in 2.7. lots of other
password updates in the new versions too.
https://github.com/processwire/processwire

**Comment by gRegorLove** [comment]
Ah, is 2.8 in /processwire/processwire repo as well? I didn't realize that.

**Comment by adrianbj** [comment]
Currently still here: https://github.com/ryancramerdesign/pw28

But I believe it's coming over to the processwire organization shortly.

**Comment by gRegorLove** [comment]
Gotcha. Good to know. I might recommend a note at the top of the ryancramerdesign/processwire repo linking to the other ones. I've always gone there out of habit so didn't realize things were in different repos. :) Closing this since no issue.
