### ISSUE TITLE
Please add a CSV helper to $wire->files

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-requests#400]
### Short description of the enhancement

As I have already stated in the [creating 20 million pages](https://processwire.com/talk/topic/25444-creating-20-million-pages/) thread I think it would be great to abstract the complexity of reading CSV files to something more PW-genius like that:

```php
$file = "/my/large/file.csv";
$options = [
  'delimiter' => ',',
  'length' => 100, // largest line length in bytes
  'headers' => true, // use first line as array keys
];

// prepare template and parent
$tpl = $templates->get('foo');
$parent = $pages->get(123);

// loop all rows
while($line = $files->readCSV($file, $options)) {
  $p = $this->wire(new Page());
  $p->template = $tpl;
  $p->parent = $parent;
  $p->title = $line['Foo Column']; // access data via header name
  $p->body = $line['Bar Column']; // access data via header name
  $p->save();
}
```

### Current vs. suggested behavior

The thread explains well which problems one has to tackle every time working with CSV files. `$wire->files` is always at our hands, so it would make a lot of sense to add `$wire->files->readCSV()` that takes care of all the complexity.

### Why would the enhancement be useful to users?

Working with CSV is a common need! We have several modules like https://processwire.com/modules/import-pages-csv/ of course, but they do not help us when working with large files or when dealing with special cases...

If you think this addition would be helpful give it a **thumb up**, thx :)

**PS: Don't use other emojies! Github can only sort issues by ONE emoji**

**Comment by fuzenco** [comment]
This would be a beyond-great addition to PW. I really hope it can happen.

**Comment by andy-scboy** [comment]
I need this function

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock good idea, I have added this. 

cc: @fuzenco @andy-scboy

**Comment by fuzenco** [comment]
@

> Thanks @BernhardBaumrock good idea, I have added this.
> 
> cc: @fuzenco @andy-scboy

@ryancramerdesign amazing! Thank you.
