### ISSUE TITLE
Support JPEG XL (.jxl)

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#407]
This is a more of a request for something in the distant future (6 months to 1-2 years perhaps), but JPEG XL (extension is .jxl) is now a new image format.

Info:
- https://jpegxl.info/
- hacker news comments: https://news.ycombinator.com/item?id=27577328
- caniuse: https://caniuse.com/jpegxl

**Comment by adrianbj** [comment]
And I thought AVIF was the next big thing. Thanks for bringing attention to JXL. 

For those interested in the current support for these:
https://caniuse.com/jpegxl vs https://caniuse.com/avif

**Comment by jlahijani** [comment]
It's been abandoned by Chrome.  https://news.ycombinator.com/item?id=33933208

Closing.
