### ISSUE TITLE
Do not include multiple site profiles in the main PW repo; make them available separately

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#415]
I downloaded the latest PW dev version (v3.0.183) from GitHub, unzipped, then rezipped the files into two groupings:

- All the site profiles apart from site-blank
- Everything else

This is the result:

![2021-08-13_121611](https://user-images.githubusercontent.com/1538852/129285790-ccd3d5c4-363d-478b-860e-b0e37bcc921b.png)

So the extra site profiles beyond the minimum needed to install PW make up 53% of the total download size of the PW repo.

I'm sure that the range of site profiles are useful to users who are brand new to PW and so I would want them to be always available. But I'm questioning whether including all the site profiles in the main PW repo passes a cost/benefit analysis.

It would be difficult to get hard data on this so I think it will require guestimating, but if we consider the total downloads from the PW repo, what proportion is...
1. For an upgrade of an existing installation, maybe via the ProcessWireUpgrade module? 
2. For a new installation by a user who knows which site profile they will install?
3. For a new installation by a user who doesn't know which site profile they will install, presumably because they are a new user who doesn't yet understand what site profiles are and how the bundled profiles differ?

At my guestimate this these 3 scenarios would make up 99%+ of downloads (maybe some tiny percentage of people download the repo just to explore it without any intention to install or update PW).

Of the 3 scenarios...

The user in scenario 1 doesn't need any site profiles.

The user in scenario 2 needs only a single site profile. We can't know in advance which profile that will be, but if we decided that we were only going to bundle a single profile in the PW download then it seems like site-blank would be the best candidate because...

- It is the most minimal profile which makes the fewest assumptions about how PW will be used.
- It is the smallest profile by an order of magnitude, adding only 12kB to the download size.
- It will in fact be the profile that is desired by some proportion of the users. I don't know what proportion, but personally speaking: starting with day 2 of using PW it has been the only bundled profile that I have ever installed.

The user in scenario 3 will probably appreciate having multiple site profiles to choose from. Although trying out different profiles is not exactly easy. It requires multiple installations because you can't change from one profile to another after install. This actually confused me a bit when I first encountered PW. 
Does this user need 6 profiles? Not sure, but let's say yes for arguments sake.

My guess is that scenarios 1 and 2 make up the big majority of total PW downloads. And by bundling 6 site profiles with every download we are (slightly) more than doubling the size that must be downloaded.

For scenarios 1 and 2 this is a negative because:

- Downloading takes twice the time it would otherwise take.
- Some users may be paying for data, or have a data cap on their internet connection.
- It's pointless/wasteful. This is my main gripe really - PW as a tool is lean and efficient, so it feels wrong to transfer data over the wire and then immediately discard 53% of it. And it's not just a philosophical thing - for example there is growing public discussion about the climate change cost of internet activity. I think it might be overblown but still something to consider.

So could we halve the size of the PW repo and still provide a nearly-as-good experience to new users? My thoughts are:

Move each site profile besides site-blank to a new official repo (one per profile) within https://github.com/processwire/, e.g. https://github.com/processwire/site-regular/
My impression is that the site profiles are only rarely updated so there wouldn't be a lot of extra maintenance burden to separate them like this. 

The PW installer offers the choice to install the bundled site-blank profile or to "download and install" one of the supported remote site profiles. The list of supported profiles would probably be hard-coded in the installer but could possibly use the GitHub API to list all repos under https://github.com/processwire/ which start with "site-". Besides the "download and install" option which would download/unzip/continue the installer would also show a download link to each profile in case the user wants/needs to download and unzip the profile manually.

Maybe there are other ways to rethink the site profiles aspect of the PW repo, and I'm keen to have other people suggest ideas too.

**Comment by szabeszg** [comment]
> So could we halve the size of the PW repo and still provide a nearly-as-good experience to new users? My thoughts are:
> 
> Move each site profile besides site-blank to a new official repo (one per profile) within https://github.com/processwire/, e.g. https://github.com/processwire/site-regular/
> My impression is that the site profiles are only rarely updated so there wouldn't be a lot of extra maintenance burden to separate them like this.
> 
> The PW installer offers the choice to install the bundled site-blank profile or to "download and install" one of the supported remote site profiles. The list of supported profiles would probably be hard-coded in the installer but could possibly use the GitHub API to list all repos under https://github.com/processwire/ which start with "site-". Besides the "download and install" option which would download/unzip/continue the installer would also show a download link to each profile in case the user wants/needs to download and unzip the profile manually.

+1 :)

**Comment by ryancramerdesign** [comment]
@Toutouwai I've had similar thoughts but didn't realize the profiles took up that much space. If that's the case, it definitely makes sense to separate them. The next master version will likely be the last one that includes all the current profiles, and we'll move any heavy profiles to their own repos on the next dev branch (maybe leaving just blank profile). I think this approach also encourages more 3rd party profiles since it makes the separation between core and profile more obvious. I'm not sure about having the installer http download profiles, as that opens new security concerns. But we can look closer at it when the time comes to work on this.

**Comment by Toutouwai** [comment]
@ryancramerdesign, big thanks for actioning this in the latest dev release.
