### ISSUE TITLE
findRaw should have support for joining parents and references

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-requests#427]
### The problem

Here is an example with a normal find operation that uses page.parent and page.parent.parent where the request times out or takes ages because it iterates over so much pages (over 15000):
```
// get the field motiv_bestellteMenge from the parent.parent, but only if the status_order field of the parent is 2 or 3
$count = $pages->find("template=padorder_product_motiv, parent.pad_status_order=2|3, parent.parent.pad_shopid=$pp");
foreach($count as $c){
$out += $c->motiv_bestellteMenge;
}
```
Another problem are page references:
I want to display a table of all customers and their related shops and some fields from the parent page of the customer. In the 
"Shops" column you find the edit links of references to this customer.
![image](https://user-images.githubusercontent.com/551551/146942893-52e4e928-c0da-492a-977a-1a98846186da.png)

Bernhard has support for joins in RockFinder3https://processwire.com/modules/rock-finder3/#joins which is a bit slower than the native findRaw method.

This is the query in RockFinder
```
$finder = new RockFinder("template=kunde, has_parent=kunden, sort=title", [
  'title',
  'ku_type',
  'ku_strasse',
  'ku_hausNr',
  'ku_plz',
  'ku_ort',
  'shops' => function($page) {
    $shops = $this->pages->find("template=shop,referenceKunde=$page->id");
    return $shops->implode(function($item) {
      return "<li><a href='../page/edit/?id=" . $item->id . "'>$item->title</a></li>";
    }, array('prepend' => '<ul>', 'append' => '</ul>'));
  },
]);
```

This is the findRaw code that I use right now to get the references to the customers:
```
public function executeGetCustomers(){
    $tabulator = $this->modules->get('ProcessWireTabulatorJs');
    $result = $this->pages->findRaw("template=kunde",["id", "title","ku_type","ku_strasse","ku_hausNr","ku_plz","ku_ort", ["objects" => "true"]]);
    // get all options for ku_type field
    $field = $this->fields->get('ku_type');
    $ku_types = $field->type->getOptions($field);

	// now join the shops reference into the shops column
    foreach($result as $kunde){
      $shops = $this->pages->findRaw("template=shop,referenceKunde={$kunde['id']}",["id","title"]);
//      bd($kunde['ku_type'][0]);
      $result[$kunde['id']]['ku_type'] = $this->returnOptionsTitle($kunde['ku_type'][0], $ku_types);
      if (count($shops) > 0){
        $result[$kunde['id']]["shops"] = '<ul>';
        foreach($shops as $shop){
          $result[$kunde['id']]["shops"] .= "<li><a href='../page/edit/?id=" . $shop['id'] . "'>{$shop['title']}</a></li>";
        }
        $result[$kunde['id']]["shops"] .= '</ul>';
      }
    }
//    bd($result);
    if($this->config->ajax){
      header('Content-Type: application/json');
      echo $tabulator->convertFindRawToJson($result);
      die();
    }
  }
```
As you can I have to iterate over the customers and do an additional findRaw query for each customer to get its references which is very cumbersome and means additional processing overhead.

### The solution
Add support for $page.parent and $page.parent.parent and also page.references to the findRaw method.

This was also requested by multiple people in the forums for example from Adrian and https://processwire.com/talk/topic/25088-pw-30172-%E2%80%93-find-faster-and-more-efficiently/?do=findComment&comment=211944

### Additional optimizations
Support for getting option titles (from an options field) would also be a great addition and is something that RockFinder also provides: https://processwire.com/modules/rock-finder3/#working-with-options-fields

I need option titles also in my tabulator grid (see the type column in my screenshot and my code:
```
public function returnOptionsTitle($value, $optionsArray){
    return $optionsArray->get("id=$value")->title;
  }
```
Note: There is also a request for getting image variants with findRaw: https://processwire.com/talk/topic/26254-findraw-and-images

**Comment by ryancramerdesign** [comment]
@jmartsch When it comes to "parent", can you give me a simplified example of the type of findRaw you would want to do? For instance, is what you are looking for basically this sort of thing?
~~~~~
$pages->findRaw("selector string", [ "parent.some_field", "parent.another_field" ]); 
~~~~~

**Comment by jmartsch** [comment]
> @jmartsch When it comes to "parent", can you give me a simplified example of the type of findRaw you would want to do? For instance, is what you are looking for basically this sort of thing?
> 
> ```
> $pages->findRaw("selector string", [ "parent.some_field", "parent.another_field" ]); 
> ```

Hey Ryan, this is exactly what I want to to, and also query a field from a parent.parent like:
`$pages->findRaw("selector string", [ "parent.some_field", "parent.parent.a_field" ]);`

**Comment by ryancramerdesign** [comment]
@jmartsch Okay, I can add that pretty easily. Actually it was [already started in the code](https://github.com/processwire/processwire/blob/master/wire/core/PagesRaw.php#L496) and it won't take much code to complete it.

**Comment by jmartsch** [comment]
A little addition as described in my initial request:
the parent and parent.parent can be part of the selector, and then I need the field "motiv_bestellteMenge" of the page with the template "padorder_product_motiv"  if the parent selectors are matching. Like
```
$count = $pages->find("template=padorder_product_motiv, parent.pad_status_order=2|3, parent.parent.pad_shopid=$pp");
foreach($count as $c){
$out += $c->motiv_bestellteMenge;
}
```

**Comment by ryancramerdesign** [comment]
@jmartsch You can already use "parent.parent.field" in selectors to find or findRaw, so I'm not sure I understand the request. Can you expand on that?

**Comment by jmartsch** [comment]
@ryancramerdesign I thought these selectors do not work, because the find request 
``` 
$motifs = $pages->findRaw("template=padorder_product_motiv, motiv_id=564030,parent.parent.pad_status_order=3", 'id,title');
d($motifs);
``` 
always times out (Maximum execution time of 120 seconds exceeded) if I use a parent.parent selector. 
Without any parent selector the request is very fast.
I have many parent.parent pages, that are being iterated and checked (about 16000). I suspect that parent and parent.parent selectors in findRaw are not so efficient as they could be, but I don't really know.

**Comment by ryancramerdesign** [comment]
@jmartsch All page finding queries are handled by PageFinder, whether originating from pages.find() or pages.findRaw() or pages.get() or anything else. So the parent.parent.* stuff is not part of findRaw(). Testing parent.parent.* queries here it performs fast, but I'm sure there's something different about your install than mine. I'm thinking it might relate to something about the field, environment or scale, along with some other factor that's different. First thing I would look at is your field pad_status_order... is that an integer field? See if you can get some other parent.parent condition to work quickly, this might help to identify where the bottleneck could be, like if it's related to the field being queried or something else. I'll do some more testing here too to see if I can identify anything too.

**Comment by jmartsch** [comment]
@ryancramerdesign So basically if I understand you correctly you are saying that parent.parent selectors do not use the fast findRaw query, but instead always request a page with all its autoaded fields. Do I understand this correctly?

If so, I think this would be the bottleneck because first the parents of all pages with the template "padorder_product_motiv" are requested with their autoloaded fields, and then the parents of these parents are also requested with their autoloaded fields, which means much overhead and memory consumption.

If I just do a simple $pages->find operation it already takes around 20 seconds and uses about 200 MB of memory.
`$motifs = $pages->find("template=padorder,pad_status_order=3,pad_status_production=2");`
![image](https://user-images.githubusercontent.com/551551/149375588-b60c22ea-060a-4f7a-a4b7-f15a1362f007.png)

## How I think it should work
What I am asking for if my assumptions are correct, is that if I use a parent or parent.parent selector is to also use the fast findRaw  to just get the required fields.
For example if I try to get all the pages that match my query 
`$motifs = $pages->findRaw("template=padorder_product_motiv, motiv_id=564030,parent.parent.pad_status_order=3", 'id,title');`
the find action would first get all pages with the template "padorder_product_motiv" and then just get the field "parent_id" id of the parent so the parent.parent could be determined. 
After that just the "pad_status_order" field of the parent.parent would be queried, and no autoloaded fields would be used.
Then the result would only output the pages that match the selector.

I hope that I have explained this in a reasonably understandable way.

## Second part  to describe my setup a little bit more specific
It is an e-commerce site which uses Padloper. 
The orders are stored in /processwire/setup/padloper and have the following structure
padorder
--padorder_product
----padorder_product_motiv

The orders (template padorder) are the pages being requested when I use the parent.parent selector. On these pages the status_order field has the type "Select Options".

**Comment by ryancramerdesign** [comment]
@jmartsch There is no separate findRaw query, as all queries run through the same PageFinder. What findRaw does is that it loads unprocessed raw arrays of data rather than pages, which is what makes it fast. But as far as the actual finding of what pages will match, that's the same between find(), findRaw() and everything else.

**Comment by 3fingers-com** [comment]
Hello @ryancramerdesign is there a way to have files field added to findRaw and getRaw method? It looks like they don't get recognised.
