### ISSUE TITLE
Please make the processCSV method hookable

### ISSUE THREAD

**Issue by juergenweb** [processwire/processwire-requests#436]
### Short description of the enhancement

It would be great if you will add the 3 uncerscores to the processCSV method of the [ProcessLanguage class](https://github.com/processwire/processwire/blob/master/wire/modules/LanguageSupport/ProcessLanguage.module). This method is not hookable by default at the moment.

### Optional: Steps that explain the enhancement

In my case need to hook this method to add translations to fields created by a module (Take a look at the blog post at [https://processwire.com/talk/topic/26765-module-translations-hooking-after-translation-csv-file-was-imported-and-saved/#comment-221611](https://processwire.com/talk/topic/26765-module-translations-hooking-after-translation-csv-file-was-imported-and-saved/#comment-221611l)

You only have to add 3 underscores and nothing more. ;-)

**Comment by ryancramerdesign** [comment]
No problem, I will make sure it is hookable in the next dev branch version
3.0.195. If you'd like feel free to add the 3 underscores to your copy and
it'll be present on the next update.

**Comment by juergenweb** [comment]
Thank you!!!!
