### ISSUE TITLE
Add usage information on field edit page

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-requests#445]
When you edit a template, a "Usage" fieldset at the bottom of the Basics tab shows pages with that template. It would be nice to have similar Usage info for fields, displaying a list of all templates where the edited field is used.

**Comment by jmartsch** [comment]
I agree, that this would be useful.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik This information is already on the Actions tab > Add or remove field from templates.  That's why it's not duplicated again on a Usage field... but I suppose it could be.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign Yes, I know it's there. I thought it might be better to have this in the same tab as we have it on Templates. As a new user, I wouldn't consider going to _Actions -> Add or remove field from templates_ to see the usage. Feel free to close this request if you find it not worthwhile.

**Comment by matjazpotocnik** [comment]
Thank you.
