### ISSUE TITLE
add check for memory limit on install

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-requests#449]
### Short description of the enhancement

We had a support request in the forum shortly. Turned out the memory limit was set to 16MB: https://processwire.com/talk/topic/27321-blank-screen-after-clean-installation/#comment-225035

I thought it might be nice to add a check to the installer?

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I have added this. I'm not exactly sure what PW's minimum memory_limit requirement is but am thinking somewhere between 32 and 64 M. However, I think 128 M or more should be the current recommendation.
