### ISSUE TITLE
Add support for getting page template name in $pages->findRaw()

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#457]
### Short description of the enhancement

It would be nice to be able to get the template name of pages in the array returned by `$pages->findRaw()`, maybe by using a syntax like `template.name` in the `$fields` argument.

Currently you can get the template ID by using `templates_id` in `$fields` but often the template name is preferred and that then requires the developer to do a separate step to translate the template IDs to names. It would be handy if `findRaw()` could take care of that.

**Comment by ryancramerdesign** [comment]
@Toutouwai Good idea, thanks. I have added this.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign
