### ISSUE TITLE
Documentation request: additional arguments for Page::render()

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-requests#459]
[Docs page for Page](https://processwire.com/api/ref/page) currently states that Page::render() accepts only one argument, which is the field name:

$page->render($fieldName = '') | string mixed | Returns rendered page markup. If given a $fieldName argument, it behaves same as the renderField() method.Can also be used as property: $page->render
-- | -- | --

Meanwhile the [docs page for PageRender::renderPage()](https://processwire.com/api/ref/page-render/render-page/) explains that you can also pass an array of custom variables in, and that this method actually accepts two arguments:

> This method provides the implementation for $page->render() and you sould only call this method as render() from Page objects. You may optionally specify 1-2 arguments to the method. The first argument may be an array of options OR filename (string) to render. If specifying a filename in the first argument, you can optionally specify the $options array as the 2nd argument.

---

Additional confusion arises from the fact that according to Page docs Page::render() only accepts **field**name, while according to PageRender::renderPage() docs page it only accepts **file**name or options array.

I see that there's a "before" hook that changes the behaviour depending on whether the first argument looks like a field name, so PageRender::renderPage() docs page is not _wrong_, but it's still confusing when trying to figure out what Page::render() actually does/accepts (assuming that one has come this far in the first place) :)

---

... and finally, if a field name is passed as an argument to Page::render(), it actually accepts two arguments: field name and file name. Currently that behaviour doesn't seem to be documented.

**Comment by teppokoivula** [comment]
Note: additional confusion arises from the fact that according to Page docs `Page::render()` only accepts **field**name, while according to PageRender::renderPage() it only accepts **file**name or options array.

I get that there's a "before" hook that changes the behaviour depending on whether the first argument looks like a field name, so technically PageRender docs page is not wrong, but it's still confusing for someone trying to figure out what `Page::render()` actually does/accepts (assuming that they've come this far in the first place) :)

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula those are good observations. I have pushed updates to the documentation for this to the dev branch, and it will appear in the live documentation once I update the ProcessWire version running the website.

**Comment by teppokoivula** [comment]
Thanks, Ryan!
