### ISSUE TITLE
Multilanguage support for module config fields

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#46]
### Short description of the enhancement

Ability to use multilanguage fields in module config settings.

### Why would the enhancement be useful to users?

I think many modules could benefit from the ability to define multilanguage versions of text. Forum post here: https://processwire.com/talk/topic/5825-multi-language-support-for-module-config-fields/

Would it be simple enough (ish) to store the different language versions in the module json paired to the id of the language?

**Comment by CanRau** [comment]
have a look at https://github.com/CanRau/MarkupCookieConsent/ it's got already multi lang config fields

**Comment by adrianbj** [comment]
Thanks @CanRau - super easy to implement - thanks for letting me know!
