### ISSUE TITLE
Documentation request: bundling translations with module

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-requests#464]
Bundling translations with module code is explained in https://processwire.com/blog/posts/pw-3.0.181-hello/, but this is difficult to find, even when you already have an idea what to look for. Just had to do that, and since Google only found unrelated results from the forum, I ended up having to step through a number of recent posts to find the correct one.

It would be great to have this documented in the multi-language docs section instead of as a part of a blog post.

Loosely related: for whatever reason our blog posts don't seem to rank all that well in Google. I'm not sure if this is anything to be worried about, but it does make it somewhat tricky to find content from within the blog. Might be worthwhile to check via Google Search Console tools that there aren't any crawling issues dragging the blog down.

**Comment by ryancramerdesign** [comment]
@teppokoivula Good idea, I have added a new page for it here:
https://processwire.com/docs/modules/development/multi-language-translations/

And it is linked on the multi-language page here as well:
https://processwire.com/docs/multi-language-support/

**Comment by teppokoivula** [comment]
Thank you! 👏
