### ISSUE TITLE
Template order in InputFieldSelector to alphabetical

### ISSUE THREAD

**Issue by j4rnonie** [processwire/processwire-requests#466]
We have a long list of templates in use and choosing the right template from the InputFieldSelector drop down is pain in the butt as current order is based on template name, but it is shown in select option as template title (in most configurations).

My suggestion : 
add : 
if( $showFieldLabels > 0) asort(templates); 
before row https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module#L423

**Comment by ryancramerdesign** [comment]
Thanks @j4rnonie I have added this, as well as corrected it in a couple other spots in the same file.

**Comment by jmartsch** [comment]
Thank you @ryancramerdesign. I also wanted this badly.

**Comment by j4rnonie** [comment]
Thanks Ryan!
