### ISSUE TITLE
Ability to expand/collapse a repeater item's children (and grandchildren, etc.) items

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#474]
Repeaters currently have Item Depth and Family Friendly capability.

Family friendly allows you to drag a repeater item and move it's 'child items' with it, which is very convenient.

In the same spirit, would it be possible to develop expand/collapse capability so that if you "collapse" a repeater item, it's child items become hidden, and if you "expand" they re-appear?  This is basically the same concept as code-folding in a text-editor (or folders within folders... you get the idea).

This would require some visual UI adjustments to indicate expand or collapsed state.

It would also be excellent if the expand/collapsed state was stored and maintained yielding the same state if you came back to the page at a later time.

**Comment by szabeszg** [comment]
I think this request belongs to the Repeater Matrix "Family settings" feature set that's been planned for more than a year, see:
https://processwire.com/blog/posts/new-repeater-and-repeater-matrix-features/

> What’s next?
> Still on the to-do list for Repeater Matrix is to add the ability to control what item types are allowed where, kind of like the Family settings on page templates.

Currently, matrix item depth is a some sort of "half baked" feature, I would love to see it receive full fledged parent/child relationship treatment, a long with features implemented by Robin:
https://processwire.com/modules/restrict-repeater-matrix/

Right now, admin users are prone to all sorts of mistakes they can make while working with complex repeater setups. Any new features that help to avoid any of them are welcome.

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani I have added this.
