### ISSUE TITLE
Make LazyCron timeFuncs public

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-requests#485]
### Short description of the enhancement

I'd like to use https://github.com/processwire/processwire/blob/6ff498f503db118d5b6c190b35bd937b38b80a77/wire/modules/LazyCron.module#L96 array for select options in module configs.
Is it possible to change this from protected to public?

**Comment by BernhardBaumrock** [comment]
That plus a static function that returns the seconds for a given timestring :)

```php
$seconds = LazyCron::seconds('every2Hours'); // 7200
```

**Comment by ryancramerdesign** [comment]
@gebeer As a best practice I don't usually make module properties public since one could then modify the value, but I've added a `getTimeFuncs` method that makes that info available. 

@BernhardBaumrock I've added a `getTimeFuncSeconds()` that will return that info.

**Comment by gebeer** [comment]
Thank you Ryan.
