### ISSUE TITLE
WireHTTP more http methods

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#505]
WireHTTP supports these methods:

```
protected $allowHttpMethods = array('GET', 'POST', 'PUT', 'DELETE', 'HEAD', 'PATCH'); 
```

Would it be possible to add 'OPTIONS' and 'CONNECT' and 'TRACE'?  'OPTIONS' is definitely useful when working with 3rd party APIs (including the AppAPI PW module, which itself is a API creator for ProcessWire).

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani I have added those http methods to the allowed list in WireHttp. To use them, you would use the WireHttp::send() method.
