### ISSUE TITLE
Allow Email for Forgot Password (instead of just Username)

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#51]
### Short description of the enhancement

The forgot password module only allows you to enter a username (which is technically a page name) as the account identifying piece of information.  It does not support an email field, which is understandable since that's not a system field and may not exist as a field on the User template on some sites, or even if a site contained an email field, it may not be truly unique like a page name.  However I feel it's more memorable for a user to remember their email rather than their username.  Perhaps the module can be modified to overcome the above caveats and allow for email field usage.

### Why would the enhancement be useful to users?

(explained above)

**Comment by szabeszg** [comment]
I like the idea too. In the module's settings it might be possible to specify the field used for the email. If it is not unique, let's send separate emails for each match, for example.

**Comment by ivangretsky** [comment]
It might be not exactly what is needed, but [this module](https://processwire.com/talk/topic/10517-frontend-password-reset/) has this functionality.
