### ISSUE TITLE
InputfieldDatetime: provide a way of setting jQuery UI datepicker options

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#523]
### Short description of the enhancement

InputfieldDatetime can use the [jQuery UI datepicker](https://api.jqueryui.com/datepicker/), and sometimes this is forced e.g. in InputfieldSelector. The [datepicker options are hardcoded](https://github.com/processwire/processwire/blob/5fe181c315688c421fdf6fa1dce798839831dd47/wire/modules/Inputfield/InputfieldDatetime/InputfieldDatetime.js#L30-L57) and there doesn't seem to be a way to customise the options for a given datetime inputfield.

This request is for a feature where the datepicker options can be set for an InputfieldDatetime instance.

Something like:

```php
$inputfield = $this->wire()->modules->get('InputfieldDatetime');
$inputfield->datepickerOptions = [
    'minDate' => 'new Date(2007, 1 - 1, 1)',
    'constrainInput ' => false
];
```

And maybe there could be config field for this when InputfieldDatetime is used together with a PW field?

**Comment by MetaTunes** [comment]
This would be very useful as currently it seems like there is no easy way of doing a relative date comparison in InputfieldSelector.
But also need to consider how InputfieldDatetime is stored - see [discussion](https://processwire.com/talk/topic/29791-use-relative-date-input-in-datetime-field/)
