### ISSUE TITLE
Show the 404 page in page tree for non-superusers

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-requests#6]
Non-superusers can edit the 404 page if they figure out a way to navigate to that edit page, but this page isn't visible for them on the page tree. I don't see a good reason to *not* properly display the 404 page for them, while I can think of a couple of pretty good reasons (in my opinion) to display it:

- In our case the clients control all their content, but don't have access to a superuser account, as that would give them access to certain features not intended for "content editors". This means that we have to either specifically provide a link to the 404 page edit screen or, more likely, that edit requests have to go through us (which is a waste of time for everyone involved).

- The 404 page could well be seen as one of the most important pages on a site (you get sent here every time you follow a dead link, try to guess an URL but fail, etc.) and those working on the content of the site (content editors) should always make sure that it serves it's purpose. Since the 404 page isn't visible on the page tree it's all too easy to miss and forget.

- Not seeing an editable page on the page tree is confusing and leaves the impression that perhaps there's something wrong with the permission model of the site. It's simply not in line with how the page tree usually works, and every time you stumble upon something like that it makes you trust the underlying system a bit less: "if this doesn't work as expected, how can I trust that everything else does?"

This request was originally posted at https://github.com/ryancramerdesign/ProcessWire/issues/809. Reposting here since this is still causing confusion and now, almost two years later, I still feel that the current behaviour doesn't make sense.

**Comment by ryancramerdesign** [comment]
Makes sense, and simple to add, I have gone ahead and added it. It should now show the 404 page in the page list if that page happens to be editable to the user.

**Comment by cb2004** [comment]
@ryancramerdesign shouldn't the user be able to view it as well even if they cant edit it? It is a public facing part of the site after all.

Just as a sidenote, if I give the user edit permissions for the 404 template I am using then this bug is irrelevant, the count is correct, so I think the issue was it was counting the 404 for a non-superuser:

https://github.com/ryancramerdesign/ProcessWire/issues/1514

**Comment by teppokoivula** [comment]
@cb2004 In my opinion current approach makes sense. The 404 page is special, and while content editors (with edit permission on it) have a few good reasons to see it in the page tree, I can see how it could be confusing to others.

Thanks, @ryancramerdesign -- I'm closing this issue!
