### ISSUE TITLE
Markup Supports for All Input Fields

### ISSUE THREAD

**Issue by trk** [processwire/processwire-requests#62]
### InputfieldRadios, InputfieldCheckbox
Can you add markup support for all core input fields. I can modify most of inputfields markup by changing InputfieldWrapper $defaultMarkup variable by using hook.

I have a radio select on my form and after render markup look like (can't change it) :

```html
<ul>
     <li>
          <label>
               <input />
               <span>
                    <span></span>
               </span>
          </label>
     </li>
</ul>
```

**Comment by pwFoo** [comment]
Markup is hardcoded in method render(). YOu could addHookBefore and replace the entire function with custom code or just copy all the code and modify the hardcoded markup string.
https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldRadios/InputfieldRadios.module#L71

I started a feature request (#66) to make it a optional parameter to overwrite the default markup code.

**Comment by trk** [comment]
I have 200line codes for hooking lots of processwire inputs.
Something like this will be helpfull :
$inputTemplate = {inputWrapper}{labe}{input}{/label}{/inputWrapper}

You can check my no-finished module : https://github.com/trk/AvbFormBuilder/blob/master/AvbFormBuilder.module#L47

I don't want to work on it, templating like here will be very helpfull for developers
