### ISSUE TITLE
PageAutocomplete multiple pages with edit links.

### ISSUE THREAD

**Issue by elabx** [processwire/processwire-requests#65]
### Short description of the enhancement

When using PageAutocomplete inputfield with multiple pages it would be nice if the edit link would be available, just like ASM Selected.

**Comment by gmclelland** [comment]
Correct me if I wrong, but this sounds like a duplicate of https://github.com/processwire/processwire-requests/issues/61

**Comment by elabx** [comment]
You are right, it is the same request. Closing request.
