### ISSUE TITLE
Do not start a session if PW externally botstrapped

### ISSUE THREAD

**Issue by eresik** [processwire/processwire-requests#68]
### Short description of the enhancement

in ProcessWire.php replace
```php
$session = $this->wire('session', new Session($this), true);
$this->initVar('session', $session);
```
with

```php
if ($config->internal) {
   $session = $this->wire('session', new Session($this), true);
   $this->initVar('session', $session);
}
```

### Current vs. suggested behavior

Current behavior:
If PW API used from "another" application may be php warning "Session already started" (if "another" application start session after include PW index.php)

Suggested behavior:
PW should not use sessions if PW externally bootstrapped.

**Comment by LostKobrakai** [comment]
Just put this line in your config.php if you need that. Changing the default behaviour would be a mayor breaking change, which I doubt we'll be seeing.

```php
if(!$config->internal)
    $config->sessionAllow = false;
```

**Comment by eresik** [comment]
Thanks
