### ISSUE TITLE
Adding PHPLeague's Flysystem for alternative site/assets storage location

### ISSUE THREAD

**Issue by lesaff** [processwire/processwire-requests#73]
This will make PW more flexible in terms of the ability to store `site` or `assets` folder outside of the traditional file system.

http://flysystem.thephpleague.com/

What do you think?

**Comment by LostKobrakai** [comment]
I've a rough 3.x module working with flysystem, but this will not get core anytime soon I'd imagine. Ryan does keep external dependencies as thin as possible and really there's no benefit for the 95% of users.

**Comment by lesaff** [comment]
Would you mind sharing your module? I think this will benefit a lot of users since you can reduce your server storage space by separating your `site` and `assets` and store them elsewhere. People using CDN would benefit this as well.

I realize that keeping external dependencies as thin as possible makes sense but sometimes if there are some dependencies that worth adding, Flysystem would be one of them.

**Comment by LostKobrakai** [comment]
I'll do so after some polishing, it's in a rough state currently. 

> People using CDN would benefit this as well.

Keep in mind that there are lots of people out there using processwire which don't even know what a cdn is. Also the images field does inherit directly from the file field and image transformations do get a heck of a lot more difficult when you're not working with files on your local filesystem.

**Comment by uprightbass360** [comment]
Hey @LostKobrakai how far did you end up getting with this. I've got a great use for it if you are still interested in tackling it.
