### ISSUE TITLE
Max Number of Repeater Items

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-requests#8]
I ask this again here in the new format. The old request is [here](Considering directly comparable functionality has already been implemented on other repeater-like fields. Would really like to see this.).

> Briefly describe the enhancement or the feature request.

Not having the ability to specify a maximum number of items has caused problems for us with clients. Considering directly comparable functionality has already been implemented on other repeater-like fields, can we not replicate the behaviour of those and implement it for repeaters.

> What is the current and suggested behavior?

Just to limit the number that are output on the front-end.

> Why would the enhancement be useful to users?

Perhaps it doesn't matter when us developers are adding in content, but a lot of our clients like to add content themselves, and sometimes they even require training on how to add content ProcessWire. ProcessWire is extremely easy to use when just editing content, but that is from the perspective of someone who is technically adept. A client just see buttons and form elements they can click that just "do" different things. A lot of clients don't read instructions (let alone any emails sent to them), and just try things and come back to us when it "doesn't work".

One client didn't realise you had to click on the little "Select" button next to the page title when interacting with a Page field to actually select the page, and then wondered why it was still linking to a different page.

@ryancramerdesign, I know you are against the idea of this. But this has already been implemented for files/image fields, and in an abstract sense, they are functionally identical.

Applying a limit more than the current number of items in the repeater after creation doesn't necessarily have to incur the automatic destruction of data. The repeater items can just stay there (but won't be output on the front-end), and a warning can be shown to the user saying that any excess repeater items will not be shown.

**Comment by ryancramerdesign** [comment]
> I know you are against the idea of this. 

I'm not against the idea, and of course happy to have the request here so we can gauge interest. But I've always seen it as a front-end matter, rather a back-end one. An emphasis of PW is keeping out of front-end matters as much as possible for long term portability of content. It's a general intention, not a rule or anything. But in PW, when you need an specific limit on the front-end, you should always specify one. So in the case of a repeater field, you would `foreach($page->repeater->slice(0,3))` or `$page->repeater->find('limit=3')` if you wanted just 3 items for a particular front-end output purpose. So when I see a configured "max items" for something like this, it feels a little in opposition to the intended PW methodology. Though I suppose there are some contexts where it wouldn't be, but can't think of any at the moment. 

> But this has already been implemented for files/image fields, and in an abstract sense, they are functionally identical.

The purpose of this on file/image fields was primarily because they can behave as a single item, or multiple items. So the option was originally there to make that determination of whether the formatted value should be an item or an array of items. It became a "max items" per someone's request very early in the game, and maybe doesn't belong there. I could be wrong, but I've been under the impression it's rarely used other than as "0" or "1", as we've since moved the item/array toggle to a separate configuration property (something we might also add to repeaters). 

> Applying a limit more than the current number of items in the repeater after creation doesn't necessarily have to incur the automatic destruction of data. The repeater items can just stay there (but won't be output on the front-end), and a warning can be shown to the user saying that any excess repeater items will not be shown.

I'm okay with this. The excess items would just be removed by output formatting (so no auto destruction of DB data). And on the back-end, it would be enforced with JS by hiding the 'add' link after a max items was reached. So lets keep the request open and see if enough others might use it and if so, we'll add it.

**Comment by adrianbj** [comment]
I would add my vote for limiting in the backend. If a content creator creates 5 items but then only sees three on the frontend they will be confused. Yes, you could write in the description that only the first three will be used, but people don't read instructions, so they will still be confused :)

In my experience, the ability to limit content creators as much as possible is a necessity. They don't read instructions about file/image sizes/dimensions, the number of images, or the number of characters that can be entered in the textarea - we now have the ability to limit all these, and I think repeater items should probably be included in this.

**Comment by LostKobrakai** [comment]
> I could be wrong, but I've been under the impression it's rarely used other than as "0" or "1", as we've since moved the item/array toggle to a separate configuration property (something we might also add to repeaters).

I have as much prove as you, but I'd really expect it to be the other way round.

**Comment by ryancramerdesign** [comment]
> Yes, you could write in the description that only the first three will be used, but people don't read instructions, so they will still be confused :)

What's the purpose of having a description field then? I've never run into a client that just starts doing stuff without reading any labels or description that accompanies it. I think it's a very reasonable expectation. Though it is important to keep such descriptions short and to the point. 

> … and I think repeater items should probably be included in this.

Thanks for your feedback, we'll count this as another vote in favor and will continue to gauge interest. 

> I have as much prove as you, but I'd really expect it to be the other way round. 

I have nothing to prove, not sure I understand what you mean? Or do you mean about the configuration property I mentioned? What I was referring to about adding to repeaters was a toggle for Page vs. PageArray output formatting, so that a non-matrix repeater could perform in the same manner as a Page field.

**Comment by adrianbj** [comment]
> I've never run into a client that just starts doing stuff without reading any labels or description that accompanies it.

I want to trade clients :)

**Comment by CaelanStewart** [comment]
@ryancramerdesign, if there is a button there that says "Add New" they're probably going to click it if they want to.

I have had a use case for limiting the number of items in some repeaters for most sites I have developed.

Look at http://folkestoneharbourarm.co.uk/

Those three image boxes underneath the "Today's Weather" section use a repeater. It's just a generic repeater field which I called "Text, Link & Image repeater". By doing it this way, instead of creating three separate sets of fields, it looks organised in the back end, they can be reordered etc, and there can be less than three, but not more. The design will not allow for it. I had to put in ALL CAPS in the description that only three or less are allowed. Yet, the button to add another one is still there, and the system didn't complain when another one is added and saved. That seems like a contradiction.

**Comment by gRegorLove** [comment]
I'm in favor of the front-end methodology you described, Ryan, though not strongly opposed to it in the backend. I've certainly experienced clients not properly using certain fields, but it's been easy for us to correct by adding a documentation page.

My anecdata on max images: I've always used 0 or 1.

**Comment by adrianbj** [comment]
Just throwing in my thoughts regarding the image setting. Honestly I think I always use 0 or 1 too, but I actually thinking the repeater scenario is very different. If the client uploads too many images they probably won't care if a few are not shown, but if they have created too many repeater items and the frontend code just dismisses those over the limit, they will probably be less happy as those  excluded ones may have been more important than the ones that made it. Does that make sense?

**Comment by CaelanStewart** [comment]
Regards,
Caelan Stewart

**Comment by CaelanStewart** [comment]
And plus, if it's there, you don't have to use it. But it wouldn't hurt if it were there, and at least it'd have consistent functionality with similar fields. 

It can only save time in the long run, and I can't see this being a lot of work to implement.

Regards,
Caelan Stewart

**Comment by teppokoivula** [comment]
First of all, this is what I wrote in the original thread:

> To be honest I don't have strong opinions on this, but in the past I have had to deal with users adding more items than are displayed on the front-end, and then asking me to "fix it". When I've told them that this limitation is explained in the description of said field, the answer is something along the lines of "sorry, didn't read that – it was possible to add more so..."
> 
> Sure, we can say that it was a user error, but the GUI would be more obvious if it was indeed possible to limit the ability to add more than X items. I'm mentioning this strictly from usability point of view, so feel free to disregard if it's not in line with other important design principles :)

Now, having read what others have to say about this and having thought about it a bit more, I must say that I'm definitely for this addition. I've got plenty of experience with busy, non-technical users and one thing I can say is that no matter how hard we try to guide them with instructions, there will always be those who miss these completely.

Personally I'm a big fan of predictable user interfaces, and in my opinion the interface should always guide the user in whatever it is that they're doing. If there's a button labeled "add new", I'm going to assume that it adds a new item, and if I can add a new item, it doesn't seem too far fetched to think that it should behave like the existing items.

"If your interface needs instructions, it needs to be redesigned" is a quote I can very much relate to. Of course things are not always black or white, and no design principle should be blindly followed, but in the field of usability this is actually a pretty damn good guideline :)

**Comment by kixe** [comment]
+1 from me. Input should always be analogous to the output. If there is a limitation in the frontend (e.g. due to design considerations) there should be the same limitation in the backend.

**Comment by ivangretsky** [comment]
I came here just to propose the same thing (and not only to repeaters, but to Page Table as well). This is something very useful if the admin area is used for someone other than superusers.

The other option that can be added if to freeze the number of items after initial creation and or have a predefined array of items. This can also solve a lot of cases.

**Comment by rolandtoth** [comment]
Leaving the extra items in place would be in fact a feature imo. They could serve as a backup, or extra items that could be moved up in case the editor needs them. 

There should be a clear separator (eg a line) to show that items above this separator are "used" and others below it are not. I'm sure this could be tweaked more but I guess you got the idea.

**Comment by CaelanStewart** [comment]
@ryancramerdesign, OK, so it's been a while, there's been some clear interest in this. 

And plus, on the Friday just previous, a client added an extra repeater item (in a place where the design could only allow for three), and because I hadn't imposed the limit on the front-end, the client was wondering why the page looked "broken".

What's the final verdict on this, @ryancramerdesign?

**Comment by ghost** [comment]
@CaelanStewart there's a module for this https://processwire.com/talk/topic/14869-limit-repeater/

**Comment by CaelanStewart** [comment]
Epic! Thank you for letting me know of this, and thank you, Robin S.

But, I must say, installing a module just to add a limit to the number of items in a repeater sounds overkill. I still firmly believe that something like this should be in the core.

**Comment by thetuningspoon** [comment]
This is in core now, correct? Should be closed.
