### ISSUE TITLE
Simple tooltip with the field name in admin

### ISSUE THREAD

**Issue by tomfrit** [processwire/processwire-requests#81]
I would really like a simple tooltip for the input fields in the admin that shows the field name. I often find myself jumping back and forth between page tree and templates to find the field names while working with the API. Maybe only add it in developement mode, so it won't confuse the poor clients and users.

**Comment by adrianbj** [comment]
That functionality already exists - mouseoever the down arrow at the right of the field:

![screen shot 2017-03-09 at 7 40 35 am](https://cloud.githubusercontent.com/assets/871211/23757457/c29ce08c-049b-11e7-9471-6b75eea0c058.png)

That said, I really like to use the version that is in AdminOnSteroids which is a little nicer in my opinion. Also there is the excellent HelperFieldLinks if you want extra info about the fields: http://modules.processwire.com/modules/helper-field-links/

**Comment by tomfrit** [comment]
Ha! Thanks a lot, not sure why I've not seen this yet.
