### ISSUE TITLE
"Edit next" button action (without Save)

### ISSUE THREAD

**Issue by ottogal** [processwire/processwire-requests#85]
This is (slightly modified) my Comment on [http://processwire.com/blog/posts/pw-3.0.24/](http://processwire.com/blog/posts/pw-3.0.24/)

### Current vs. suggested behavior

In addition to the very useful “Save and edit next” button action I would like to have just an "Edit next" button action too.

### Why would the enhancement be useful to users?

Often I am screening some property or setting through many siblings and find me doing these unnessecary Saves just to profit of the helpful "Edit next" action.

**Comment by LostKobrakai** [comment]
It simply should be hookable, which it currently isn't. I don't feel like adding one option after the other to the core does make any sense, especially as it would be so easy to let people manage their dropdowns on their own.

**Comment by elabx** [comment]
Would it make sense to make a request to make page save button actions hookable? 

I am trying to disappear them because I am using the Page Edit form as an editing place per user (Using AdminRestrictBranch). Currently using css/javascript to achieve this.
