### ISSUE TITLE
Decouple image-resizing functions from page related storage concerns

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-requests#89]
### Short description of the enhancement

Handling images with processwire, which are not currently associated to a Page (e.g. from FormBuilder) can not simply be converted to a Pageimage and have methods like size/width/… available, because they would be copied around and related to a Page. It would be nice if the resizing behaviour would be a separate thing to the whole page files management.

**Comment by ryancramerdesign** [comment]
Image resize and manipulation are actually already decoupled, just the API is different. The methods you see with Pageimage are largely just an interface on top of the ImageSizer class. The ImageSizer class has no requirement for Page objects. All it needs is the filename. Below is an example, but it has many manipulation methods. 
~~~
$sizer = new ImageSizer('/path/to/file.jpg');
$sizer->resize(400, 300); 
// original file is now resized to 400x300
~~~~

**Comment by LostKobrakai** [comment]
I'm mostly missing the "in place" filename handling so things are not created more than once.
