### ISSUE TITLE
Composing Selectors

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-requests#9]
> Briefly describe the enhancement or the feature request.

Allowing the reuse of arbitrary selectors as custom selector properties.

Considering a projects website, where old projects a archived under a different parent than active ones. One might often need to differentiate them even though other selectors are the same.

It would be nice if the selector could be stored somewhere:

`isArchive => "template=projects, name=archive"`

And could be used in a selector e.g. like this: "template=posts, parent=^isArchive"
which would expand to this: "template=posts, parent=[template=projects, name=archive]"

> What is the current and suggested behavior?

Copy and paste the selector for each usage.

> Why would the enhancement be useful to users?

Does allow users to avoid the need of duplicating selector parts.

**Comment by teppokoivula** [comment]
Perhaps I'm missing the point here, but isn't this basically the same thing as storing selectors in a variable? At least that's how I usually solve a need like this :)

With stuff like this it's difficult to keep things obvious and readable: your syntax example, for an example, reads to me like "starts with isArchive". The more "special features" our selectors get, less expressive they become.
