### ISSUE TITLE
Add name property to all Children and Settings tab fields and fieldsets

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-requests#90]
### Short description of the enhancement

Add name property to all Children and Settings tab fields

### Current vs. suggested behavior

Currently, fields like "Children / Subpages" on the Children tab only have the label property as a way to target them. It would be very helpful to have a name property.

### Why would the enhancement be useful to users?

As an example, because the label of the Children tab can be changed in the template > advanced settings, the label for "Children / Subpages" will also be changed to match this. There are also the multi-language implications here. You can see how I had to deal with this in my BatchChildEditor module with this recent commit: https://github.com/adrianbj/BatchChildEditor/commit/2e5aababd9975e6abfa69e821237771c592f9389

If it had a name property, it would be much simpler. I think this should also be applied to other fields/fieldsets like "Sort Settings" (children tab) and all those on the settings tab.

**Comment by ryancramerdesign** [comment]
Sounds good, I agree. I am adding this now.

**Comment by matjazpotocnik** [comment]
@adrianbj, can you confirm that this is now in core, as Ryan stated?

**Comment by adrianbj** [comment]
Hi @matjazpotocnik - looks like @ryancramerdesign actually added an `id` rather than a `name` but in my quick tests that works just as well for the needs I had when I posted this request, so happy to close.
